#!/usr/bin/env python3
"""Dump selected facstd components of a determinant active-set ideal."""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from gtz63_semialgebraic import determinant_text_system, singular_order, text_system_summary  # noqa: E402
from probe_determinant_ideals import resolve_active, singular_string  # noqa: E402


def write_script(system, path: Path, order: str, characteristic: int, out_dir: Path) -> None:
    varlist = ",".join(system.variables)
    out_dir.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Generated by code/sage/dump_facstd_components.py",
        f"// active_indices: {list(system.active_indices)}",
        f"// characteristic: {characteristic}",
        "timer = 1;",
        f"ring r = {characteristic},({varlist}),({singular_order(order)});",
        "",
    ]
    for i, expr in enumerate(system.equalities):
        lines.append(f"poly f{i} = {expr};")
    lines.append(f"ideal I = {','.join(f'f{i}' for i in range(len(system.equalities)))};")
    lines.extend([
        "option(redSB);",
        "list L = facstd(I);",
        f"{singular_string('facstd_components')};",
        "size(L);",
        "int k;",
        "for (k=1; k<=size(L); k++) {",
        f"  {singular_string('component')};",
        "  k;",
        "  ideal G = std(L[k]);",
        f"  {singular_string('basis_size')};",
        "  size(G);",
        f"  {singular_string('dimension')};",
        "  dim(G);",
        f"  {singular_string('degree')};",
        "  degree(G);",
        "  if (dim(G) > 0) {",
        f"    string p = {singular_string(str(out_dir) + '/component_')} + string(k) + {singular_string('_std_basis.txt')};",
        "    write(p, G);",
        f"    {singular_string('basis_path')};",
        "    p;",
        "  }",
        "}",
        f"{singular_string('timer')};",
        "timer;",
        "quit;",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def parse_output(stdout: str) -> dict:
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    keys = {
        "facstd_components",
        "component",
        "basis_size",
        "dimension",
        "degree",
        "basis_path",
        "timer",
    }
    parsed: dict[str, object] = {}
    components = []
    current = None
    pending_degree_target = None
    i = 0
    while i < len(lines):
        line = lines[i]
        if pending_degree_target is not None:
            match = re.search(r"degree \([^)]+\)\s*=\s*(-?\d+)", line)
            if match:
                pending_degree_target["degree_value"] = int(match.group(1))
                pending_degree_target = None
                i += 1
                continue
        if line not in keys or i + 1 >= len(lines):
            i += 1
            continue
        raw = lines[i + 1]
        try:
            value: object = int(raw)
        except ValueError:
            value = raw
        if line == "component":
            current = {"component": value}
            components.append(current)
        elif current is not None and line in {"basis_size", "dimension", "degree", "basis_path"}:
            current[line] = value
            if line == "degree":
                pending_degree_target = current
        else:
            parsed[line] = value
            if line == "degree":
                pending_degree_target = parsed
        i += 2
    parsed["components"] = components
    return parsed


def run_singular(script_path: Path, singular_bin: str, timeout: int) -> dict:
    start = time.monotonic()
    try:
        completed = subprocess.run(
            [singular_bin, "-q", str(script_path)],
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        elapsed = time.monotonic() - start
        return {
            "timed_out": False,
            "exit_code": completed.returncode,
            "elapsed_seconds": elapsed,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "had_error": "? ERROR" in completed.stdout or "? error" in completed.stdout,
            "parsed": parse_output(completed.stdout),
        }
    except subprocess.TimeoutExpired as exc:
        elapsed = time.monotonic() - start
        stdout = exc.stdout or ""
        stderr = exc.stderr or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode(errors="replace")
        if isinstance(stderr, bytes):
            stderr = stderr.decode(errors="replace")
        return {
            "timed_out": True,
            "exit_code": None,
            "elapsed_seconds": elapsed,
            "stdout": stdout,
            "stderr": stderr,
            "had_error": "? ERROR" in stdout or "? error" in stdout,
            "parsed": parse_output(stdout),
        }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--active-indices")
    parser.add_argument("--mask")
    parser.add_argument("--known-label")
    parser.add_argument("--order", default="degrevlex")
    parser.add_argument("--invert-d", action="store_true")
    parser.add_argument("--timeout", type=int, default=300)
    parser.add_argument("--characteristic", type=int, default=32003)
    parser.add_argument("--singular-bin", default=shutil.which("Singular") or "Singular")
    parser.add_argument("--out-prefix", default="code/sage/out/fac_components")
    args = parser.parse_args()

    active = resolve_active(args)
    system = determinant_text_system(active, order=args.order, invert_d=args.invert_d)
    out_prefix = Path(args.out_prefix)
    out_dir = out_prefix.with_name(f"{out_prefix.name}_components")
    script_path = out_prefix.with_suffix(".sing")
    write_script(system, script_path, args.order, args.characteristic, out_dir)
    run = run_singular(script_path, args.singular_bin, args.timeout)
    result = {
        "summary": text_system_summary(system),
        "characteristic": args.characteristic,
        "timeout_seconds": args.timeout,
        "script": str(script_path),
        "component_dir": str(out_dir),
        "run": run,
    }
    result_path = out_prefix.with_suffix(".json")
    result_path.write_text(json.dumps(result, indent=1) + "\n")

    parsed = run.get("parsed", {})
    components = parsed.get("components", []) if isinstance(parsed, dict) else []
    positive = [row for row in components if row.get("dimension", 0) > 0]
    status = "timeout" if run["timed_out"] else f"exit {run['exit_code']}"
    print(
        f"facstd: {status}, elapsed={run['elapsed_seconds']:.1f}s, "
        f"components={len(components)}, positive_dim={len(positive)}"
    )
    for row in positive:
        print(row)
    print(f"wrote {result_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
