#!/usr/bin/env python3
"""Dump a Groebner basis for a determinant active-set ideal."""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import time
from dataclasses import replace
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from gtz63_semialgebraic import determinant_text_system, singular_order, text_system_summary  # noqa: E402
from lexify_determinant_slice import equality_degree, parse_equalities  # noqa: E402
from probe_determinant_ideals import resolve_active, singular_string  # noqa: E402


def write_script(system, path: Path, basis_path: Path, method: str, order: str, characteristic: int) -> None:
    varlist = ",".join(system.variables)
    lines = [
        "// Generated by code/sage/dump_determinant_gb.py",
        f"// method: {method}",
        f"// active_indices: {list(system.active_indices)}",
        f"// characteristic: {characteristic}",
        "timer = 1;",
        f"ring r = {characteristic},({varlist}),({singular_order(order)});",
        "",
    ]
    for i, expr in enumerate(system.equalities):
        lines.append(f"poly f{i} = {expr};")
    lines.append(f"ideal I = {','.join(f'f{i}' for i in range(len(system.equalities)))};")
    lines.extend([
        "",
        f"{singular_string('method')};",
        f"{singular_string(method)};",
        f"{singular_string('nvars')};",
        f"{len(system.variables)};",
        f"{singular_string('neqs')};",
        f"{len(system.equalities)};",
        f"{singular_string('characteristic')};",
        f"{characteristic};",
        "option(redSB);",
    ])
    if method == "std":
        lines.append("ideal G = std(I);")
    elif method == "slimgb":
        lines.append("ideal G = slimgb(I);")
    elif method == "modstd":
        lines.extend(['LIB "modstd.lib";', "ideal G = modStd(I, 0);"])
    elif method == "modslimgb":
        lines.extend(['LIB "modstd.lib";', 'ideal G = modGB("slimgb", I, 0);'])
    else:
        raise ValueError(f"unknown method: {method}")
    lines.extend([
        f"{singular_string('basis_size')};",
        "size(G);",
        f"{singular_string('dimension')};",
        "dim(G);",
        f"{singular_string('vdim')};",
        "vdim(G);",
        f"{singular_string('degree')};",
        "degree(G);",
        f"write({singular_string(str(basis_path))}, G);",
        f"{singular_string('basis_path')};",
        f"{singular_string(str(basis_path))};",
        f"{singular_string('timer')};",
        "timer;",
        "quit;",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def parse_output(stdout: str) -> dict:
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    keys = {
        "method",
        "nvars",
        "neqs",
        "characteristic",
        "basis_size",
        "dimension",
        "vdim",
        "degree",
        "basis_path",
        "timer",
    }
    parsed: dict[str, object] = {}
    pending_degree = False
    i = 0
    while i < len(lines):
        line = lines[i]
        if pending_degree:
            match = re.search(r"degree \([^)]+\)\s*=\s*(-?\d+)", line)
            if match:
                parsed["degree_value"] = int(match.group(1))
                pending_degree = False
                i += 1
                continue
        if line not in keys or i + 1 >= len(lines):
            i += 1
            continue
        raw = lines[i + 1]
        try:
            value: object = int(raw)
        except ValueError:
            value = raw
        parsed[line] = value
        if line == "degree":
            pending_degree = True
        i += 2
    return parsed


def run_singular(script_path: Path, singular_bin: str, timeout: int) -> dict:
    start = time.monotonic()
    try:
        completed = subprocess.run(
            [singular_bin, "-q", str(script_path)],
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        elapsed = time.monotonic() - start
        return {
            "timed_out": False,
            "exit_code": completed.returncode,
            "elapsed_seconds": elapsed,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "had_error": "? ERROR" in completed.stdout or "? error" in completed.stdout,
            "parsed": parse_output(completed.stdout),
        }
    except subprocess.TimeoutExpired as exc:
        elapsed = time.monotonic() - start
        stdout = exc.stdout or ""
        stderr = exc.stderr or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode(errors="replace")
        if isinstance(stderr, bytes):
            stderr = stderr.decode(errors="replace")
        return {
            "timed_out": True,
            "exit_code": None,
            "elapsed_seconds": elapsed,
            "stdout": stdout,
            "stderr": stderr,
            "had_error": "? ERROR" in stdout or "? error" in stdout,
            "parsed": parse_output(stdout),
        }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--active-indices")
    parser.add_argument("--mask")
    parser.add_argument("--known-label")
    parser.add_argument("--order", default="degrevlex")
    parser.add_argument("--invert-d", action="store_true")
    parser.add_argument("--method", choices=["std", "slimgb", "modstd", "modslimgb"], default="slimgb")
    parser.add_argument("--timeout", type=int, default=300)
    parser.add_argument("--characteristic", type=int, default=0)
    parser.add_argument("--singular-bin", default=shutil.which("Singular") or "Singular")
    parser.add_argument("--extra-equalities", default="")
    parser.add_argument("--out-prefix", default="code/sage/out/det_gb")
    args = parser.parse_args()

    active = resolve_active(args)
    system = determinant_text_system(active, order=args.order, invert_d=args.invert_d)
    extras = parse_equalities(args.extra_equalities)
    if extras:
        system = replace(
            system,
            mode=f"{system.mode}_extra_equalities",
            equalities=system.equalities + extras,
            equality_degrees=system.equality_degrees + tuple(equality_degree(eq) for eq in extras),
            metadata={**system.metadata, "extra_equalities": list(extras)},
        )
    out_prefix = Path(args.out_prefix)
    script_path = out_prefix.with_suffix(".sing")
    basis_path = out_prefix.with_name(f"{out_prefix.name}_basis.txt")
    write_script(system, script_path, basis_path, args.method, args.order, args.characteristic)
    run = run_singular(script_path, args.singular_bin, args.timeout)
    result = {
        "summary": text_system_summary(system),
        "characteristic": args.characteristic,
        "timeout_seconds": args.timeout,
        "method": args.method,
        "script": str(script_path),
        "basis_path": str(basis_path),
        "run": run,
    }
    result_path = out_prefix.with_suffix(".json")
    result_path.write_text(json.dumps(result, indent=1) + "\n")
    parsed = run.get("parsed", {})
    status = "timeout" if run["timed_out"] else f"exit {run['exit_code']}"
    print(
        f"{args.method}: {status}, elapsed={run['elapsed_seconds']:.1f}s, "
        f"dim={parsed.get('dimension', '?') if isinstance(parsed, dict) else '?'}, "
        f"degree={parsed.get('degree_value', '?') if isinstance(parsed, dict) else '?'}, "
        f"basis={parsed.get('basis_size', '?') if isinstance(parsed, dict) else '?'}"
    )
    print(f"wrote {result_path}")
    if basis_path.exists():
        print(f"wrote {basis_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
