#!/usr/bin/env python3
"""Compute a lex basis for a zero-dimensional determinant slice.

This is the exact follow-up to ``probe_determinant_ideals.py``: after a
determinant system plus linear sections has been observed to be
zero-dimensional, compute a Groebner basis in degree order and convert it to a
lex basis with FGLM.
"""
from __future__ import annotations

import argparse
import json
import random
import re
import shutil
import subprocess
import sys
import time
from dataclasses import replace
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from gtz63_semialgebraic import (  # noqa: E402
    determinant_text_system,
    singular_order,
    text_system_summary,
)
from probe_determinant_ideals import (  # noqa: E402
    random_linear_forms,
    resolve_active,
    singular_string,
    zero_sum_z_linear_forms,
)
from probe_minor_relation import minor_relation_text, parse_minor_rows  # noqa: E402


def lex_variable_order(variables: tuple[str, ...], last_variable: str) -> tuple[str, ...]:
    if last_variable not in variables:
        raise ValueError(f"{last_variable!r} is not in variables {variables}")
    return tuple(name for name in variables if name != last_variable) + (last_variable,)


def write_lex_script(
    system,
    path: Path,
    method: str,
    order: str,
    characteristic: int,
    linear_forms: tuple[str, ...],
    lex_variables: tuple[str, ...],
    lex_basis_path: Path,
) -> None:
    varlist = ",".join(system.variables)
    lex_varlist = ",".join(lex_variables)
    lines = [
        "// Generated by code/sage/lexify_determinant_slice.py",
        f"// method: {method}",
        f"// active_indices: {list(system.active_indices)}",
        f"// characteristic: {characteristic}",
        "timer = 1;",
        f"ring r = {characteristic},({varlist}),({singular_order(order)});",
        "",
    ]
    for i, expr in enumerate(system.equalities):
        lines.append(f"poly f{i} = {expr};")
    if system.equalities:
        lines.append(f"ideal I = {','.join(f'f{i}' for i in range(len(system.equalities)))};")
    else:
        lines.append("ideal I = 0;")
    for i, expr in enumerate(linear_forms):
        lines.append(f"poly l{i} = {expr};")
    if linear_forms:
        lines.append(f"I = I,{','.join(f'l{i}' for i in range(len(linear_forms)))};")

    lines.extend([
        "",
        f"{singular_string('method')};",
        f"{singular_string(method)};",
        f"{singular_string('nvars')};",
        f"{len(system.variables)};",
        f"{singular_string('neqs')};",
        f"{len(system.equalities)};",
        f"{singular_string('linear_sections')};",
        f"{len(linear_forms)};",
        f"{singular_string('max_degree')};",
        f"{max(system.equality_degrees) if system.equality_degrees else 0};",
        f"{singular_string('characteristic')};",
        f"{characteristic};",
        "option(redSB);",
    ])

    if method == "std":
        lines.append("ideal G = std(I);")
    elif method == "slimgb":
        lines.append("ideal G = slimgb(I);")
    elif method == "modstd":
        lines.extend([
            'LIB "modstd.lib";',
            "ideal G = modStd(I, 0);",
        ])
    elif method == "modslimgb":
        lines.extend([
            'LIB "modstd.lib";',
            'ideal G = modGB("slimgb", I, 0);',
        ])
    else:
        raise ValueError(f"unknown method: {method}")

    lines.extend([
        f"{singular_string('gb_basis_size')};",
        "size(G);",
        f"{singular_string('gb_dimension')};",
        "dim(G);",
        f"{singular_string('gb_vdim')};",
        "vdim(G);",
        f"{singular_string('gb_degree')};",
        "degree(G);",
        f"{singular_string('lex_variable_order')};",
        f"{singular_string(','.join(lex_variables))};",
        "if (dim(G) == 0)",
        "{",
        f"  ring s = {characteristic},({lex_varlist}),(lp);",
        "  ideal H = fglm(r, G);",
        f"  {singular_string('lex_basis_size')};",
        "  size(H);",
        f"  {singular_string('lex_vdim')};",
        "  vdim(H);",
        f"  {singular_string('lex_first_poly')};",
        "  H[1];",
        f"  {singular_string('lex_last_poly')};",
        "  H[size(H)];",
        f"  write({singular_string(str(lex_basis_path))}, H);",
        f"  {singular_string('lex_basis_path')};",
        f"  {singular_string(str(lex_basis_path))};",
        "}",
        "else",
        "{",
        f"  {singular_string('lex_skipped')};",
        f"  {singular_string('gb_not_zero_dimensional')};",
        "}",
        f"{singular_string('timer')};",
        "timer;",
        "quit;",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def parse_singular_output(stdout: str) -> dict:
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    parsed: dict[str, object] = {}
    keys = {
        "method",
        "nvars",
        "neqs",
        "linear_sections",
        "max_degree",
        "characteristic",
        "gb_basis_size",
        "gb_dimension",
        "gb_vdim",
        "gb_degree",
        "lex_variable_order",
        "lex_basis_size",
        "lex_vdim",
        "lex_first_poly",
        "lex_last_poly",
        "lex_basis_path",
        "lex_skipped",
        "timer",
    }
    pending_degree = False
    i = 0
    while i < len(lines):
        line = lines[i]
        if pending_degree:
            match = re.search(r"degree \([^)]+\)\s*=\s*(-?\d+)", line)
            if match:
                parsed["gb_degree_value"] = int(match.group(1))
                pending_degree = False
                i += 1
                continue
        if line not in keys or i + 1 >= len(lines):
            i += 1
            continue
        raw_value = lines[i + 1]
        try:
            value: object = int(raw_value)
        except ValueError:
            value = raw_value
        parsed[line] = value
        if line == "gb_degree":
            pending_degree = True
        i += 2
    return parsed


def run_singular(script_path: Path, singular_bin: str, timeout: int) -> dict:
    start = time.monotonic()
    try:
        completed = subprocess.run(
            [singular_bin, "-q", str(script_path)],
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        elapsed = time.monotonic() - start
        return {
            "timed_out": False,
            "exit_code": completed.returncode,
            "elapsed_seconds": elapsed,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "had_error": "? ERROR" in completed.stdout or "? error" in completed.stdout,
            "parsed": parse_singular_output(completed.stdout),
        }
    except subprocess.TimeoutExpired as exc:
        elapsed = time.monotonic() - start
        stdout = exc.stdout or ""
        stderr = exc.stderr or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode(errors="replace")
        if isinstance(stderr, bytes):
            stderr = stderr.decode(errors="replace")
        return {
            "timed_out": True,
            "exit_code": None,
            "elapsed_seconds": elapsed,
            "stdout": stdout,
            "stderr": stderr,
            "had_error": "? ERROR" in stdout or "? error" in stdout,
            "parsed": parse_singular_output(stdout),
        }


def split_singular_ideal(text: str) -> list[str]:
    return [part.strip() for part in text.replace("\n", "").split(",") if part.strip()]


def variables_in_polynomial(poly: str, variables: tuple[str, ...]) -> list[str]:
    found = []
    for variable in variables:
        pattern = rf"(?<![A-Za-z0-9_]){re.escape(variable)}(?![A-Za-z0-9_])"
        if re.search(pattern, poly):
            found.append(variable)
    return found


def parse_equalities(text: str) -> tuple[str, ...]:
    return tuple(item.strip() for item in text.split(",") if item.strip())


def primitive_linear_expression(
    variable: str,
    variables: tuple[str, ...],
    seed: int,
    coefficient_bound: int,
) -> tuple[str, dict]:
    rng = random.Random(seed)
    z_variables = [name for name in variables if name.startswith("z")]
    if len(z_variables) != 9:
        raise ValueError(f"expected 9 z variables, got {z_variables}")
    coeffs = []
    for _name in z_variables:
        coeff = 0
        while coeff == 0:
            coeff = rng.randint(-coefficient_bound, coefficient_bound)
        coeffs.append(coeff)
    linear = " + ".join(f"({coeff})*{name}" for coeff, name in zip(coeffs, z_variables))
    return f"{variable} - ({linear})", {"variable": variable, "coefficients": dict(zip(z_variables, coeffs))}


def parse_compact_rows(text: str) -> tuple[int, int]:
    if "," in text:
        return parse_minor_rows(text)
    rows = tuple(int(char) for char in text.strip())
    if len(rows) != 2 or len(set(rows)) != 2 or any(row < 0 or row >= 3 for row in rows):
        raise SystemExit("minor rows must be two distinct local row indices, e.g. 02 or 0,2")
    return rows


def parse_relation_specs(text: str) -> tuple[tuple[int, tuple[int, int], int, str], ...]:
    specs = []
    for item in text.split(";"):
        item = item.strip()
        if not item:
            continue
        parts = item.split(":")
        if len(parts) != 4:
            raise SystemExit(
                "--extra-minor-relations entries must have active:rows:coefficient:variable, "
                "for example 1:12:46656:z1"
            )
        active_index, rows_text, coefficient, variable = parts
        specs.append((int(active_index), parse_compact_rows(rows_text), int(coefficient), variable))
    return tuple(specs)


def equality_degree(text: str) -> int:
    if "^" not in text and "*" not in text:
        return 1
    degree = 1
    for chunk in text.replace("-", "+").split("+"):
        factors = [factor.strip() for factor in chunk.split("*") if factor.strip()]
        term_degree = 0
        for factor in factors:
            if "^" in factor:
                try:
                    term_degree += int(factor.rsplit("^", 1)[1])
                except ValueError:
                    term_degree += 1
            elif factor:
                term_degree += 1
        degree = max(degree, term_degree)
    return degree


def summarize_lex_basis(path: Path, variables: tuple[str, ...]) -> dict:
    if not path.exists():
        return {"exists": False}
    text = path.read_text().strip()
    polynomials = split_singular_ideal(text)
    univariate = []
    for index, poly in enumerate(polynomials, start=1):
        vars_here = variables_in_polynomial(poly, variables)
        if len(vars_here) == 1:
            univariate.append({
                "index": index,
                "variable": vars_here[0],
                "polynomial": poly,
            })
    return {
        "exists": True,
        "path": str(path),
        "polynomial_count": len(polynomials),
        "univariate_polynomials": univariate,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--active-indices")
    parser.add_argument("--mask")
    parser.add_argument("--known-label")
    parser.add_argument("--order", default="degrevlex")
    parser.add_argument("--invert-d", action="store_true")
    parser.add_argument(
        "--method",
        choices=["std", "slimgb", "modstd", "modslimgb"],
        default="modslimgb",
    )
    parser.add_argument("--timeout", type=int, default=600)
    parser.add_argument("--characteristic", type=int, default=0)
    parser.add_argument("--singular-bin", default=shutil.which("Singular") or "Singular")
    parser.add_argument("--out-prefix", default="code/sage/out/lex_det_slice")
    parser.add_argument("--linear-sections", type=int, default=0)
    parser.add_argument(
        "--linear-section-mode",
        choices=["random", "zero-sum-z"],
        default="random",
    )
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--coefficient-bound", type=int, default=17)
    parser.add_argument("--lex-last-variable", default="z0")
    parser.add_argument("--add-minor-relation", action="store_true")
    parser.add_argument("--minor-active-index", type=int, default=1)
    parser.add_argument("--minor-rows", default="0,2")
    parser.add_argument("--coefficient", type=int, default=46656)
    parser.add_argument("--variable", default="z0")
    parser.add_argument(
        "--extra-minor-relations",
        default="",
        help="semicolon-separated active:rows:coefficient:variable entries, e.g. 1:12:46656:z1",
    )
    parser.add_argument(
        "--extra-equalities",
        default="",
        help="comma-separated extra equations appended before linear sections",
    )
    parser.add_argument(
        "--target-nonzero-relation",
        default="",
        help=(
            "single active:rows:coefficient:variable relation encoded as nonzero "
            "by appending a_rel*relation-1"
        ),
    )
    parser.add_argument(
        "--primitive-linear-variable",
        default="",
        help="append a new variable equal to a random linear form in z0,...,z8",
    )
    parser.add_argument("--primitive-linear-seed", type=int, default=1)
    parser.add_argument("--primitive-linear-bound", type=int, default=19)
    args = parser.parse_args()

    active = resolve_active(args)
    system = determinant_text_system(active, order=args.order, invert_d=args.invert_d)
    extra_metadata = {}
    relation_specs = []
    if args.add_minor_relation:
        relation_specs.append(
            (args.minor_active_index, parse_minor_rows(args.minor_rows), args.coefficient, args.variable)
        )
    relation_specs.extend(parse_relation_specs(args.extra_minor_relations))
    if relation_specs:
        relation_records = []
        relations = []
        relation_degrees = []
        for active_index, minor_rows, coefficient, variable in relation_specs:
            relation, relation_degree = minor_relation_text(
                active_index=active_index,
                minor_rows=minor_rows,
                coefficient=coefficient,
                order=args.order,
                invert_d=args.invert_d,
                variable=variable,
            )
            relation_records.append({
                "active_index": active_index,
                "minor_rows": list(minor_rows),
                "coefficient": coefficient,
                "variable": variable,
                "text": relation,
                "degree": relation_degree,
            })
            relations.append(relation)
            relation_degrees.append(relation_degree)
        extra_metadata["minor_relations"] = relation_records
        system = replace(
            system,
            mode=f"{system.mode}_minor_relation",
            equalities=system.equalities + tuple(relations),
            equality_degrees=system.equality_degrees + tuple(relation_degrees),
            metadata={**system.metadata, **extra_metadata},
        )
    extra_equalities = parse_equalities(args.extra_equalities)
    if extra_equalities:
        extra_metadata["extra_equalities"] = list(extra_equalities)
        system = replace(
            system,
            mode=f"{system.mode}_extra_equalities",
            equalities=system.equalities + extra_equalities,
            equality_degrees=system.equality_degrees
            + tuple(equality_degree(eq) for eq in extra_equalities),
            metadata={**system.metadata, **extra_metadata},
        )
    target_specs = parse_relation_specs(args.target_nonzero_relation)
    if target_specs:
        if len(target_specs) != 1:
            raise SystemExit("--target-nonzero-relation must contain exactly one relation spec")
        active_index, minor_rows, coefficient, variable = target_specs[0]
        relation, relation_degree = minor_relation_text(
            active_index=active_index,
            minor_rows=minor_rows,
            coefficient=coefficient,
            order=args.order,
            invert_d=args.invert_d,
            variable=variable,
        )
        target_record = {
            "active_index": active_index,
            "minor_rows": list(minor_rows),
            "coefficient": coefficient,
            "variable": variable,
            "text": relation,
            "degree": relation_degree,
            "encoded_by": "a_rel*relation-1",
        }
        extra_metadata["target_nonzero_relation"] = target_record
        system = replace(
            system,
            mode=f"{system.mode}_target_nonzero",
            variables=system.variables + ("a_rel",),
            equalities=system.equalities + (f"a_rel*({relation}) - 1",),
            equality_degrees=system.equality_degrees + (relation_degree + 1,),
            metadata={**system.metadata, **extra_metadata},
        )
    if args.primitive_linear_variable:
        if args.primitive_linear_variable in system.variables:
            raise SystemExit(f"primitive variable {args.primitive_linear_variable!r} already exists")
        expression, primitive_record = primitive_linear_expression(
            args.primitive_linear_variable,
            system.variables,
            seed=args.primitive_linear_seed,
            coefficient_bound=args.primitive_linear_bound,
        )
        extra_metadata["primitive_linear_variable"] = primitive_record
        system = replace(
            system,
            mode=f"{system.mode}_primitive_linear",
            variables=system.variables + (args.primitive_linear_variable,),
            equalities=system.equalities + (expression,),
            equality_degrees=system.equality_degrees + (1,),
            metadata={**system.metadata, **extra_metadata},
        )
    if args.linear_section_mode == "random":
        linear_forms = random_linear_forms(
            system.variables,
            count=args.linear_sections,
            seed=args.seed,
            characteristic=args.characteristic,
            coefficient_bound=args.coefficient_bound,
        )
    else:
        linear_forms = zero_sum_z_linear_forms(
            system.variables,
            count=args.linear_sections,
            seed=args.seed,
            coefficient_bound=args.coefficient_bound,
        )
    out_prefix = Path(args.out_prefix)
    out_prefix.parent.mkdir(parents=True, exist_ok=True)
    script_path = out_prefix.with_suffix(".sing")
    lex_basis_path = out_prefix.with_name(f"{out_prefix.name}_lex_basis.txt")
    lex_variables = lex_variable_order(system.variables, args.lex_last_variable)

    write_lex_script(
        system,
        script_path,
        method=args.method,
        order=args.order,
        characteristic=args.characteristic,
        linear_forms=linear_forms,
        lex_variables=lex_variables,
        lex_basis_path=lex_basis_path,
    )
    run = run_singular(script_path, args.singular_bin, args.timeout)
    lex_summary = summarize_lex_basis(lex_basis_path, system.variables)
    results = {
        "summary": text_system_summary(system),
        "timeout_seconds": args.timeout,
        "characteristic": args.characteristic,
        "linear_sections": args.linear_sections,
        "linear_section_mode": args.linear_section_mode,
        "linear_section_seed": args.seed,
        "linear_forms": list(linear_forms),
        "method": args.method,
        "script": str(script_path),
        "singular_bin": args.singular_bin,
        "lex_last_variable": args.lex_last_variable,
        "lex_variable_order": list(lex_variables),
        "run": run,
        "lex_basis": lex_summary,
    }
    result_path = out_prefix.with_suffix(".json")
    result_path.write_text(json.dumps(results, indent=1) + "\n")

    status = "timeout" if run["timed_out"] else f"exit {run['exit_code']}"
    parsed = run.get("parsed", {})
    vdim = parsed.get("lex_vdim", "?") if isinstance(parsed, dict) else "?"
    print(f"{args.method}: {status}, elapsed={run['elapsed_seconds']:.1f}s, lex_vdim={vdim}")
    print(f"wrote {result_path}")
    if lex_summary.get("exists"):
        count = len(lex_summary.get("univariate_polynomials", []))
        print(f"wrote {lex_basis_path} ({count} univariate polynomials detected)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
