#!/usr/bin/env python3
"""Convert an exact structured size-6 ansatz basis to lex order with Singular.

This is a narrower companion to ``probe_s6_ansatz.py``.  It starts from an
already computed characteristic-zero grevlex Groebner basis, so Singular can
attempt FGLM directly instead of recomputing the branch basis from the original
determinant equations.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import time
from pathlib import Path


VARIABLES = ("a", "b", "c", "d", "q")


def singular_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def split_singular_ideal(text: str) -> list[str]:
    return [part.strip() for part in text.replace("\n", "").split(",") if part.strip()]


def variables_in_polynomial(poly: str, variables: tuple[str, ...]) -> list[str]:
    found = []
    for variable in variables:
        # Singular writes compact monomials such as ``d2q3`` instead of
        # ``d^2*q^3``.  In this ansatz all variables are one-letter names, so a
        # character scan is the robust parser for variable support.
        if variable in poly:
            found.append(variable)
    return found


def summarize_lex_basis(path: Path, variables: tuple[str, ...]) -> dict:
    if not path.exists():
        return {"exists": False}
    polynomials = split_singular_ideal(path.read_text().strip())
    univariate = []
    for index, poly in enumerate(polynomials, start=1):
        vars_here = variables_in_polynomial(poly, variables)
        if len(vars_here) == 1:
            univariate.append({"index": index, "variable": vars_here[0], "polynomial": poly})
    return {
        "exists": True,
        "path": str(path),
        "polynomial_count": len(polynomials),
        "univariate_polynomials": univariate,
    }


def parse_output(stdout: str) -> dict:
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    keys = {
        "basis_size",
        "dimension",
        "vdim",
        "degree",
        "q_factor",
        "lex_variable_order",
        "lex_basis_size",
        "lex_vdim",
        "lex_first_poly",
        "lex_last_poly",
        "lex_basis_path",
        "timer",
    }
    parsed: dict[str, object] = {}
    pending_degree = False
    i = 0
    while i < len(lines):
        line = lines[i]
        if pending_degree:
            match = re.search(r"degree \([^)]+\)\s*=\s*(-?\d+)", line)
            if match:
                parsed["degree_value"] = int(match.group(1))
                pending_degree = False
                i += 1
                continue
        if line not in keys or i + 1 >= len(lines):
            i += 1
            continue
        raw_value = lines[i + 1]
        try:
            value: object = int(raw_value)
        except ValueError:
            value = raw_value
        parsed[line] = value
        if line == "degree":
            pending_degree = True
        i += 2
    return parsed


def write_script(
    basis: list[str],
    q_factor: str,
    script_path: Path,
    lex_basis_path: Path,
    lex_variables: tuple[str, ...],
) -> None:
    varlist = ",".join(VARIABLES)
    lex_varlist = ",".join(lex_variables)
    lines = [
        "// Generated by code/sage/lexify_s6_ansatz_basis.py",
        "timer = 1;",
        f"ring r = 0,({varlist}),(dp);",
        "",
    ]
    for i, poly in enumerate(basis):
        lines.append(f"poly g{i} = {poly};")
    if q_factor:
        lines.append(f"poly qfac = {q_factor};")
        lines.append(f"ideal G = {','.join(f'g{i}' for i in range(len(basis)))},qfac;")
        lines.append("option(redSB);")
        lines.append("ideal Gstd = std(G);")
        lines.append("G = Gstd;")
    else:
        lines.append(f"ideal G = {','.join(f'g{i}' for i in range(len(basis)))};")
    lines.extend(
        [
            "option(redSB);",
            f"{singular_string('basis_size')};",
            "size(G);",
            f"{singular_string('dimension')};",
            "dim(G);",
            f"{singular_string('vdim')};",
            "vdim(G);",
            f"{singular_string('degree')};",
            "degree(G);",
            f"{singular_string('q_factor')};",
            singular_string(q_factor or "<none>") + ";",
            f"{singular_string('lex_variable_order')};",
            singular_string(",".join(lex_variables)) + ";",
            f"ring s = 0,({lex_varlist}),(lp);",
            "ideal H = fglm(r, G);",
            f"{singular_string('lex_basis_size')};",
            "size(H);",
            f"{singular_string('lex_vdim')};",
            "vdim(H);",
            f"{singular_string('lex_first_poly')};",
            "H[1];",
            f"{singular_string('lex_last_poly')};",
            "H[size(H)];",
            f"write({singular_string(str(lex_basis_path))}, H);",
            f"{singular_string('lex_basis_path')};",
            singular_string(str(lex_basis_path)) + ";",
            f"{singular_string('timer')};",
            "timer;",
            "quit;",
        ]
    )
    script_path.parent.mkdir(parents=True, exist_ok=True)
    script_path.write_text("\n".join(lines) + "\n")


def run_singular(script_path: Path, singular_bin: str, timeout: int) -> dict:
    start = time.monotonic()
    try:
        completed = subprocess.run(
            [singular_bin, "-q", str(script_path)],
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        elapsed = time.monotonic() - start
        return {
            "timed_out": False,
            "exit_code": completed.returncode,
            "elapsed_seconds": elapsed,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "had_error": "? ERROR" in completed.stdout or "? error" in completed.stdout,
            "parsed": parse_output(completed.stdout),
        }
    except subprocess.TimeoutExpired as exc:
        elapsed = time.monotonic() - start
        stdout = exc.stdout or ""
        stderr = exc.stderr or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode(errors="replace")
        if isinstance(stderr, bytes):
            stderr = stderr.decode(errors="replace")
        return {
            "timed_out": True,
            "exit_code": None,
            "elapsed_seconds": elapsed,
            "stdout": stdout,
            "stderr": stderr,
            "had_error": "? ERROR" in stdout or "? error" in stdout,
            "parsed": parse_output(stdout),
        }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--basis-json", default="code/sage/out/s6_ansatz_cplusd_QQ.json")
    parser.add_argument("--q-factor", default="", help="Optional q-polynomial factor to adjoin.")
    parser.add_argument("--lex-last-variable", default="q")
    parser.add_argument("--timeout", type=int, default=900)
    parser.add_argument("--singular-bin", default=shutil.which("Singular") or "Singular")
    parser.add_argument("--out-prefix", default="code/sage/out/s6_ansatz_cplusd_fglm_QQ")
    args = parser.parse_args()

    basis_data = json.loads(Path(args.basis_json).read_text())
    if int(basis_data.get("characteristic", -1)) != 0:
        raise SystemExit("basis JSON is not over QQ")
    if basis_data.get("order") != "degrevlex":
        raise SystemExit(f"basis JSON is not grevlex: {basis_data.get('order')!r}")
    if args.lex_last_variable not in VARIABLES:
        raise SystemExit(f"unknown lex-last variable: {args.lex_last_variable}")

    out_prefix = Path(args.out_prefix)
    script_path = out_prefix.with_suffix(".sing")
    lex_basis_path = out_prefix.with_name(f"{out_prefix.name}_lex_basis.txt")
    lex_variables = tuple(name for name in VARIABLES if name != args.lex_last_variable) + (
        args.lex_last_variable,
    )
    write_script(
        basis=basis_data["basis"],
        q_factor=args.q_factor,
        script_path=script_path,
        lex_basis_path=lex_basis_path,
        lex_variables=lex_variables,
    )
    run = run_singular(script_path, args.singular_bin, args.timeout)
    lex_summary = summarize_lex_basis(lex_basis_path, VARIABLES)
    result = {
        "basis_json": args.basis_json,
        "q_factor": args.q_factor,
        "timeout_seconds": args.timeout,
        "singular_bin": args.singular_bin,
        "script": str(script_path),
        "lex_last_variable": args.lex_last_variable,
        "lex_variable_order": list(lex_variables),
        "run": run,
        "lex_basis": lex_summary,
    }
    result_path = out_prefix.with_suffix(".json")
    result_path.parent.mkdir(parents=True, exist_ok=True)
    result_path.write_text(json.dumps(result, indent=1) + "\n")

    status = "timeout" if run["timed_out"] else f"exit {run['exit_code']}"
    parsed = run.get("parsed", {})
    lex_vdim = parsed.get("lex_vdim", "?") if isinstance(parsed, dict) else "?"
    print(f"FGLM: {status}, elapsed={run['elapsed_seconds']:.1f}s, lex_vdim={lex_vdim}")
    print(f"wrote {result_path}")
    if lex_summary.get("exists"):
        print(f"wrote {lex_basis_path} ({lex_summary['polynomial_count']} polynomials)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
