#!/usr/bin/env python3
"""Local-component diagnostics for the over-tied determinant systems.

This script is deliberately modest.  It first checks the differential behavior
of the selected equations, the reconstructed separator-basis equations, and the
omitted target equation at the refined real root.  Optionally, it writes and
runs a Singular script for the global augmented quotient over a finite field.

The global quotient probe is not a local certificate by itself; it is a cheap
screen for whether the augmented ideal is already strong enough globally.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path

from sage.all import Matrix, RDF, RealField

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from gtz63_semialgebraic import TRIPLES, singular_order  # noqa: E402
from probe_bounded_ideal_membership import (  # noqa: E402
    extra_generators_from_summary,
    parse_rows,
)
from probe_determinant_ideals import singular_string  # noqa: E402
from refine_margin_tie_root import build_system  # noqa: E402


def label(prefix: str, idx: int) -> str:
    return f"{prefix}:{idx}:{''.join(str(a) for a in TRIPLES[idx])}"


def eval_poly(poly, point, RF):
    return RF(poly(*point))


def eval_polys(polys, point, RF):
    return [eval_poly(poly, point, RF) for poly in polys]


def max_abs(values):
    return max((abs(value) for value in values), default=0)


def jacobian(polys, variables):
    return [[poly.derivative(var) for var in variables] for poly in polys]


def eval_jacobian(jac, point, RF):
    return Matrix(RF, len(jac), len(point), [RF(poly(*point)) for row in jac for poly in row])


def singular_values(matrix):
    if matrix.nrows() == 0 or matrix.ncols() == 0:
        return []
    dense = Matrix(RDF, matrix.nrows(), matrix.ncols(), [RDF(value) for value in matrix.list()])
    return [float(value) for value in dense.singular_values()]


def threshold_ranks(values, thresholds):
    return {str(threshold): sum(1 for value in values if value > threshold) for threshold in thresholds}


def parse_thresholds(text: str):
    return tuple(float(part.strip()) for part in text.split(",") if part.strip())


def singular_poly(poly) -> str:
    return f"({poly})"


def write_singular_script(
    path: Path,
    variables,
    selected,
    extra,
    target,
    characteristic: int,
    method: str,
):
    varlist = ",".join(str(var) for var in variables)
    lines = [
        "// Generated by code/sage/probe_local_component_quotient.py",
        f"// method: {method}",
        f"// characteristic: {characteristic}",
        "timer = 1;",
        f"ring r = {characteristic},({varlist}),({singular_order('degrevlex')});",
        "",
    ]
    for i, poly in enumerate(selected):
        lines.append(f"poly f{i} = {singular_poly(poly)};")
    for i, poly in enumerate(extra):
        lines.append(f"poly s{i} = {singular_poly(poly)};")
    generator_names = [f"f{i}" for i in range(len(selected))] + [f"s{i}" for i in range(len(extra))]
    lines.append(f"ideal I = {','.join(generator_names) if generator_names else '0'};")
    lines.append(f"poly h = {singular_poly(target)};")
    lines.extend(
        [
            "",
            f"{singular_string('method')};",
            f"{singular_string(method)};",
            f"{singular_string('selected_generators')};",
            f"{len(selected)};",
            f"{singular_string('extra_generators')};",
            f"{len(extra)};",
            f"{singular_string('characteristic')};",
            f"{characteristic};",
            "option(redSB);",
        ]
    )
    if method == "std":
        lines.append("ideal G = std(I);")
    elif method == "slimgb":
        lines.append("ideal G = slimgb(I);")
    else:
        raise ValueError(f"unknown Singular method {method!r}")
    lines.extend(
        [
            f"{singular_string('basis_size')};",
            "size(G);",
            f"{singular_string('dimension')};",
            "dim(G);",
            f"{singular_string('vdim')};",
            "vdim(G);",
            f"{singular_string('degree')};",
            "degree(G);",
            "poly r1 = reduce(h, G);",
            "poly r2 = reduce(h*h, G);",
            f"{singular_string('normal_h_is_zero')};",
            "r1 == 0;",
            f"{singular_string('normal_h_terms')};",
            "size(r1);",
            f"{singular_string('normal_h_degree')};",
            "deg(r1);",
            f"{singular_string('normal_h2_is_zero')};",
            "r2 == 0;",
            f"{singular_string('normal_h2_terms')};",
            "size(r2);",
            f"{singular_string('normal_h2_degree')};",
            "deg(r2);",
            f"{singular_string('timer')};",
            "timer;",
            "quit;",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def parse_singular_output(stdout: str):
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    keys = {
        "method",
        "selected_generators",
        "extra_generators",
        "characteristic",
        "basis_size",
        "dimension",
        "vdim",
        "degree",
        "normal_h_is_zero",
        "normal_h_terms",
        "normal_h_degree",
        "normal_h2_is_zero",
        "normal_h2_terms",
        "normal_h2_degree",
        "timer",
    }
    parsed = {}
    pending_degree_key = None
    i = 0
    while i < len(lines):
        line = lines[i]
        if pending_degree_key is not None:
            parsed[pending_degree_key] = line
            pending_degree_key = None
            i += 1
            continue
        if line not in keys or i + 1 >= len(lines):
            i += 1
            continue
        raw = lines[i + 1]
        try:
            value = int(raw)
        except ValueError:
            value = raw
        parsed[line] = value
        if line == "degree":
            pending_degree_key = "degree_text"
        i += 2
    return parsed


def run_singular(script_path: Path, singular_bin: str, timeout: int):
    start = time.monotonic()
    try:
        completed = subprocess.run(
            [singular_bin, "-q", str(script_path)],
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        elapsed = time.monotonic() - start
        return {
            "timed_out": False,
            "exit_code": completed.returncode,
            "elapsed_seconds": elapsed,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "parsed": parse_singular_output(completed.stdout),
        }
    except subprocess.TimeoutExpired as exc:
        elapsed = time.monotonic() - start
        stdout = exc.stdout or ""
        stderr = exc.stderr or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode(errors="replace")
        if isinstance(stderr, bytes):
            stderr = stderr.decode(errors="replace")
        return {
            "timed_out": True,
            "exit_code": None,
            "elapsed_seconds": elapsed,
            "stdout": stdout,
            "stderr": stderr,
            "parsed": parse_singular_output(stdout),
        }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--rows", required=True)
    parser.add_argument("--target-row", type=int, required=True)
    parser.add_argument("--extra-generator-summary", required=True)
    parser.add_argument("--extra-generator-limit", type=int, default=0)
    parser.add_argument("--precision", type=int, default=300)
    parser.add_argument("--rank-thresholds", default="1e-8,1e-10,1e-12")
    parser.add_argument("--order", default="degrevlex")
    parser.add_argument("--singular", action="store_true")
    parser.add_argument("--singular-method", choices=["std", "slimgb"], default="slimgb")
    parser.add_argument("--characteristic", type=int, default=32003)
    parser.add_argument("--singular-bin", default=shutil.which("Singular") or "Singular")
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument("--out-prefix", default="")
    args = parser.parse_args()

    data = json.loads(Path(args.input).read_text())
    active = tuple(data["active"])
    ties = tuple(data["ties"])
    rows = parse_rows(args.rows)
    ring, _chart, variables, polynomials, _jacobian = build_system(active, ties, args.order)
    labels = [label("active", i) for i in active] + [label("tie", i) for i in ties]
    if args.target_row in rows:
        raise SystemExit("--target-row is already among selected rows")
    if min(rows + (args.target_row,)) < 0 or max(rows + (args.target_row,)) >= len(polynomials):
        raise SystemExit(f"row index out of range for {len(polynomials)} equations")

    selected = [polynomials[i] for i in rows]
    target = polynomials[args.target_row]
    extra, extra_labels = extra_generators_from_summary(
        ring,
        args.extra_generator_summary,
        args.extra_generator_limit,
    )
    augmented = selected + extra

    RF = RealField(args.precision)
    point = [RF(str(value)) for value in data["z"]] + [RF(str(data["q"]))]
    thresholds = parse_thresholds(args.rank_thresholds)

    selected_values = eval_polys(selected, point, RF)
    extra_values = eval_polys(extra, point, RF)
    augmented_values = selected_values + extra_values
    target_value = eval_poly(target, point, RF)

    selected_jac = eval_jacobian(jacobian(selected, variables), point, RF)
    extra_jac = eval_jacobian(jacobian(extra, variables), point, RF)
    augmented_jac = eval_jacobian(jacobian(augmented, variables), point, RF)
    target_jac = eval_jacobian(jacobian([target], variables), point, RF)

    selected_sv = singular_values(selected_jac)
    extra_sv = singular_values(extra_jac)
    augmented_sv = singular_values(augmented_jac)
    target_augmented_sv = singular_values(Matrix(RF, list(augmented_jac.rows()) + list(target_jac.rows())))

    result = {
        "input": args.input,
        "active": list(active),
        "ties": list(ties),
        "selected_rows": list(rows),
        "selected_labels": [labels[i] for i in rows],
        "target_row": args.target_row,
        "target_label": labels[args.target_row],
        "extra_generator_summary": args.extra_generator_summary,
        "extra_generator_count": len(extra),
        "extra_generator_labels": extra_labels,
        "precision_bits": args.precision,
        "residuals": {
            "selected_inf": str(max_abs(selected_values)),
            "extra_inf": str(max_abs(extra_values)),
            "augmented_inf": str(max_abs(augmented_values)),
            "target": str(target_value),
            "target_abs": str(abs(target_value)),
        },
        "jacobian": {
            "variable_count": len(variables),
            "selected_shape": [selected_jac.nrows(), selected_jac.ncols()],
            "extra_shape": [extra_jac.nrows(), extra_jac.ncols()],
            "augmented_shape": [augmented_jac.nrows(), augmented_jac.ncols()],
            "selected_singular_values": selected_sv,
            "extra_singular_values": extra_sv,
            "augmented_singular_values": augmented_sv,
            "target_adjoined_singular_values": target_augmented_sv,
            "rank_thresholds": list(thresholds),
            "selected_ranks": threshold_ranks(selected_sv, thresholds),
            "extra_ranks": threshold_ranks(extra_sv, thresholds),
            "augmented_ranks": threshold_ranks(augmented_sv, thresholds),
            "target_adjoined_ranks": threshold_ranks(target_augmented_sv, thresholds),
        },
    }

    out_prefix = Path(args.out_prefix) if args.out_prefix else None
    if args.singular:
        if out_prefix is None:
            out_prefix = Path("code/sage/out/local_component_quotient")
        script_path = out_prefix.with_suffix(".sing")
        write_singular_script(
            script_path,
            variables,
            selected,
            extra,
            target,
            args.characteristic,
            args.singular_method,
        )
        run = run_singular(script_path, args.singular_bin, args.timeout)
        result["singular"] = {"script": str(script_path), **run}

    if out_prefix is not None:
        out_path = out_prefix.with_suffix(".json")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(json.dumps(result, indent=1) + "\n")
    else:
        out_path = None

    print("=" * 78)
    print("LOCAL COMPONENT QUOTIENT DIAGNOSTIC")
    print(f"input: {args.input}")
    print(f"target: row {args.target_row} {labels[args.target_row]}")
    print(f"selected rows: {list(rows)}")
    print(f"extra generators: {len(extra)}")
    print(f"selected residual inf: {result['residuals']['selected_inf']}")
    print(f"extra residual inf: {result['residuals']['extra_inf']}")
    print(f"target abs: {result['residuals']['target_abs']}")
    print(f"selected Jacobian ranks: {result['jacobian']['selected_ranks']}")
    print(f"augmented Jacobian ranks: {result['jacobian']['augmented_ranks']}")
    print(f"target-adjoined Jacobian ranks: {result['jacobian']['target_adjoined_ranks']}")
    if "singular" in result:
        run = result["singular"]
        parsed = run.get("parsed", {})
        status = "timeout" if run["timed_out"] else f"exit {run['exit_code']}"
        print(
            "singular:",
            status,
            f"elapsed={run['elapsed_seconds']:.1f}s",
            f"parsed={parsed}",
        )
    if out_path is not None:
        print(f"wrote {out_path}")
    print("=" * 78)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
