#!/usr/bin/env python3
"""Bounded-degree ideal-membership probe for over-tied determinant equations.

Given an over-tied system and a selected square basis, test whether a power of an
omitted equation h, optionally multiplied by a separator, is in the ideal
generated by the selected equations with multiplier degree bounded by D:

    s^k h^r = sum_i a_i f_i,      deg(a_i) <= D.

This is an exact linear-algebra test over QQ.  Success is a checkable global
ideal-membership certificate.  Failure is only a bounded-degree negative result.
"""
from __future__ import annotations

import argparse
import itertools
import json
import sys
from math import comb
from pathlib import Path

from sage.all import GF, Matrix, QQ, vector

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from gtz63_semialgebraic import TRIPLES  # noqa: E402
from refine_margin_tie_root import build_system  # noqa: E402


def parse_rows(text: str) -> tuple[int, ...]:
    rows = tuple(int(part.strip()) for part in text.split(",") if part.strip())
    if len(set(rows)) != len(rows):
        raise ValueError("row indices must be distinct")
    return rows


def label(prefix: str, idx: int) -> str:
    return f"{prefix}:{idx}:{''.join(str(a) for a in TRIPLES[idx])}"


def exponent_tuples(nvars: int, max_degree: int):
    def rec(pos: int, remaining: int, prefix: tuple[int, ...]):
        if pos == nvars:
            yield prefix
            return
        for value in range(remaining + 1):
            yield from rec(pos + 1, remaining - value, prefix + (value,))

    yield from rec(0, max_degree, ())


def monomial_from_exp(ring, gens, exp):
    out = ring.one()
    for gen, power in zip(gens, exp):
        if power:
            out *= gen ** power
    return out


def coefficient_field(characteristic: int):
    if characteristic == 0:
        return QQ
    return GF(characteristic)


def separator_from_file(ring, path: str):
    data = json.loads(Path(path).read_text())
    poly = ring.zero()
    for term in data["terms"]:
        poly += ring.base_ring()(term["coefficient"]) * ring(term["monomial"])
    return poly


def separator_from_terms(ring, terms):
    poly = ring.zero()
    for term in terms:
        poly += ring.base_ring()(term["coefficient"]) * ring(term["monomial"])
    return poly


def extra_generators_from_summary(ring, path: str, limit: int):
    data = json.loads(Path(path).read_text())
    basis = data.get("basis", data.get("short_separators", []))
    if limit < 0:
        raise SystemExit("--extra-generator-limit must be nonnegative")
    if limit:
        basis = basis[:limit]
    generators = []
    labels = []
    for entry in basis:
        generators.append(separator_from_terms(ring, entry["terms"]))
        if "basis_index" in entry:
            labels.append(f"separator_basis:{entry['basis_index']}")
        else:
            labels.append(f"short_separator:{entry.get('lll_row_index', len(labels))}")
    return generators, labels


def build_membership_matrix(generators, target, multiplier_degree: int, field):
    ring = target.parent()
    gens = ring.gens()
    multiplier_monomials = [
        monomial_from_exp(ring, gens, exp)
        for exp in exponent_tuples(len(gens), multiplier_degree)
    ]
    columns = []
    monomial_set = set(target.dict().keys())
    for i, gen in enumerate(generators):
        for j, monomial in enumerate(multiplier_monomials):
            poly = monomial * gen
            columns.append((i, j, poly))
            monomial_set.update(poly.dict().keys())

    monomials = sorted(monomial_set)
    row_index = {monomial: row for row, monomial in enumerate(monomials)}
    entries = {}
    for col, (_i, _j, poly) in enumerate(columns):
        for monomial, coeff in poly.dict().items():
            if coeff:
                entries[(row_index[monomial], col)] = field(coeff)
    matrix = Matrix(field, len(monomials), len(columns), entries, sparse=True)
    rhs = vector(field, len(monomials))
    for monomial, coeff in target.dict().items():
        rhs[row_index[monomial]] = field(coeff)
    return matrix, rhs, monomials, columns, multiplier_monomials


def solve_if_consistent(matrix, rhs, need_solution: bool):
    augmented = matrix.augment(rhs.column())
    rank = matrix.rank()
    augmented_rank = augmented.rank()
    if rank != augmented_rank or not need_solution:
        return rank, augmented_rank, None
    try:
        solution = matrix.solve_right(rhs)
    except Exception:
        solution = None
    return rank, augmented_rank, solution


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="over-tie refinement JSON")
    parser.add_argument("--rows", required=True, help="selected generator rows")
    parser.add_argument("--target-row", type=int, required=True)
    parser.add_argument("--target-power", type=int, default=1)
    parser.add_argument(
        "--separator",
        choices=["none", "chart-d", "q", "separator-file"],
        default="none",
        help="optional separator multiplied into the target",
    )
    parser.add_argument("--separator-power", type=int, default=1)
    parser.add_argument("--separator-file", default="", help="JSON separator file used with --separator separator-file")
    parser.add_argument(
        "--extra-generator-summary",
        action="append",
        default=[],
        help="reconstructed separator-subspace summary JSON; its basis elements are added as ideal generators",
    )
    parser.add_argument(
        "--extra-generator-limit",
        type=int,
        default=0,
        help="number of separator basis generators to use from --extra-generator-summary; 0 means all",
    )
    parser.add_argument(
        "--extra-generator-summary-limit",
        action="append",
        type=int,
        default=[],
        help="per-summary generator limit, repeated in the same order as --extra-generator-summary",
    )
    parser.add_argument("--degree", type=int, default=1)
    parser.add_argument(
        "--characteristic",
        type=int,
        default=0,
        help="0 for QQ, otherwise run the linear algebra over GF(p)",
    )
    parser.add_argument("--order", default="degrevlex")
    parser.add_argument("--write-certificate", action="store_true")
    parser.add_argument("--out", default="")
    args = parser.parse_args()

    data = json.loads(Path(args.input).read_text())
    active = tuple(data["active"])
    ties = tuple(data["ties"])
    rows = parse_rows(args.rows)
    ring, chart, _variables, polynomials, _jacobian = build_system(active, ties, args.order)
    if args.target_row in rows:
        raise SystemExit("--target-row is already among selected rows")
    if min(rows + (args.target_row,)) < 0 or max(rows + (args.target_row,)) >= len(polynomials):
        raise SystemExit(f"row index out of range for {len(polynomials)} equations")

    labels = [label("active", i) for i in active] + [label("tie", i) for i in ties]
    generators = [polynomials[i] for i in rows]
    generator_labels = [labels[i] for i in rows]
    extra_generator_labels = []
    if args.extra_generator_summary_limit and len(args.extra_generator_summary_limit) != len(args.extra_generator_summary):
        raise SystemExit("--extra-generator-summary-limit must be repeated once per --extra-generator-summary")
    for index, summary_path in enumerate(args.extra_generator_summary):
        summary_limit = (
            args.extra_generator_summary_limit[index]
            if args.extra_generator_summary_limit
            else args.extra_generator_limit
        )
        extra_generators, labels_from_summary = extra_generators_from_summary(
            ring,
            summary_path,
            summary_limit,
        )
        generators.extend(extra_generators)
        generator_labels.extend(labels_from_summary)
        extra_generator_labels.extend(labels_from_summary)
    if args.target_power < 1:
        raise SystemExit("--target-power must be positive")
    if args.separator_power < 0:
        raise SystemExit("--separator-power must be nonnegative")
    target = polynomials[args.target_row] ** args.target_power
    separator_poly = ring.one()
    if args.separator != "none" and args.separator_power:
        if args.separator == "chart-d":
            separator_poly = chart.d
        elif args.separator == "q":
            separator_poly = dict(zip(ring.variable_names(), ring.gens()))["q"]
        elif args.separator == "separator-file":
            if not args.separator_file:
                raise SystemExit("--separator-file is required with --separator separator-file")
            separator_poly = separator_from_file(ring, args.separator_file)
        target *= separator_poly ** args.separator_power
    field = coefficient_field(args.characteristic)
    estimated_multiplier_count = comb(len(ring.gens()) + args.degree, args.degree)
    print("=" * 78, flush=True)
    print("BOUNDED IDEAL MEMBERSHIP", flush=True)
    print(f"input: {args.input}", flush=True)
    print(f"target: row {args.target_row} {labels[args.target_row]}", flush=True)
    print(f"target power: {args.target_power}", flush=True)
    print(f"separator: {args.separator}^{args.separator_power if args.separator != 'none' else 0}", flush=True)
    print(f"extra generators: {len(extra_generator_labels)} from {args.extra_generator_summary or '(none)'}", flush=True)
    print(f"degree: {args.degree}", flush=True)
    print(f"field: {'QQ' if args.characteristic == 0 else 'GF(%d)' % args.characteristic}", flush=True)
    print(
        "building sparse matrix: "
        f"{len(generators)} generators x {estimated_multiplier_count} multiplier monomials "
        f"= {len(generators) * estimated_multiplier_count} columns",
        flush=True,
    )
    matrix, rhs, monomials, columns, multiplier_monomials = build_membership_matrix(
        generators, target, args.degree, field
    )
    rank, augmented_rank, solution = solve_if_consistent(matrix, rhs, args.write_certificate)
    member = bool(rank == augmented_rank)

    nonzero_solution_entries = None
    if solution is not None and args.write_certificate:
        nonzero_solution_entries = [
            {
                "generator_index": i,
                "generator_row": rows[i] if i < len(rows) else None,
                "generator_label": generator_labels[i],
                "multiplier_monomial": str(multiplier_monomials[j]),
                "coefficient": str(coeff),
            }
            for (i, j, _poly), coeff in zip(columns, solution)
            if coeff
        ]

    payload = {
        "input": args.input,
        "active": list(active),
        "ties": list(ties),
        "selected_rows": list(rows),
        "selected_labels": [labels[i] for i in rows],
        "extra_generator_summary": args.extra_generator_summary,
        "extra_generator_limit": args.extra_generator_limit,
        "extra_generator_summary_limit": args.extra_generator_summary_limit,
        "extra_generator_count": len(extra_generator_labels),
        "extra_generator_labels": extra_generator_labels,
        "target_row": args.target_row,
        "target_label": labels[args.target_row],
        "target_power": args.target_power,
        "separator": args.separator,
        "separator_power": args.separator_power if args.separator != "none" else 0,
        "multiplier_degree": args.degree,
        "characteristic": args.characteristic,
        "generator_count": len(generators),
        "multiplier_monomial_count": len(multiplier_monomials),
        "unknown_count": matrix.ncols(),
        "monomial_equation_count": matrix.nrows(),
        "matrix_rank": int(rank),
        "augmented_rank": int(augmented_rank),
        "bounded_degree_member": member,
        "certificate_terms": nonzero_solution_entries,
    }
    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(json.dumps(payload, indent=1) + "\n")

    print(f"matrix: {matrix.nrows()} x {matrix.ncols()}")
    print(f"rank: {rank}, augmented rank: {augmented_rank}")
    print(f"MEMBER: {member}")
    if args.out:
        print(f"wrote {args.out}")
    print("=" * 78)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
