#!/usr/bin/env python3
"""Probe saturated determinant active-set ideals with Singular.

Run through the Sage environment, for example:

    ~/miniforge3/bin/mamba run -n sage python \
      code/sage/probe_determinant_ideals.py --active-indices 0,1,2,3 \
      --methods slimgb --timeout 180 --out-prefix code/sage/out/probe_A0_3
"""
from __future__ import annotations

import argparse
import json
import random
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from gtz63_semialgebraic import (  # noqa: E402
    determinant_text_system,
    indices_from_mask,
    known_active_indices,
    parse_indices,
    singular_order,
    text_system_summary,
)


def resolve_active(args) -> tuple[int, ...]:
    sources = [
        args.active_indices is not None,
        args.mask is not None,
        args.known_label is not None,
    ]
    if sum(sources) != 1:
        raise SystemExit("provide exactly one of --active-indices, --mask, --known-label")
    if args.active_indices is not None:
        return parse_indices(args.active_indices)
    if args.mask is not None:
        return indices_from_mask(int(args.mask, 0))
    return known_active_indices(args.known_label)


def singular_string(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def random_linear_forms(
    variables: tuple[str, ...],
    count: int,
    seed: int,
    characteristic: int,
    coefficient_bound: int,
) -> tuple[str, ...]:
    rng = random.Random(seed)
    forms = []
    for _ in range(count):
        terms = []
        for variable in variables:
            if characteristic > 0:
                coeff = rng.randrange(1, characteristic)
            else:
                coeff = 0
                while coeff == 0:
                    coeff = rng.randint(-coefficient_bound, coefficient_bound)
            terms.append(f"({coeff})*{variable}")
        if characteristic > 0:
            constant = rng.randrange(0, characteristic)
        else:
            constant = rng.randint(-coefficient_bound, coefficient_bound)
        terms.append(f"({constant})")
        forms.append(" + ".join(terms))
    return tuple(forms)


def zero_sum_z_linear_forms(
    variables: tuple[str, ...],
    count: int,
    seed: int,
    coefficient_bound: int,
) -> tuple[str, ...]:
    rng = random.Random(seed)
    z_variables = [name for name in variables if name.startswith("z")]
    if len(z_variables) != 9:
        raise ValueError(f"expected 9 z variables, got {z_variables}")
    forms = []
    seen = set()
    while len(forms) < count:
        coeffs = [rng.randint(-coefficient_bound, coefficient_bound) for _ in range(8)]
        coeffs.append(-sum(coeffs))
        if all(coeff == 0 for coeff in coeffs):
            continue
        gcd = 0
        for coeff in coeffs:
            gcd = abs(coeff) if gcd == 0 else __import__("math").gcd(gcd, abs(coeff))
        if gcd > 1:
            coeffs = [coeff // gcd for coeff in coeffs]
        key = tuple(coeffs)
        if key in seen:
            continue
        seen.add(key)
        parts = [
            f"({coeff})*{variable}"
            for coeff, variable in zip(coeffs, z_variables)
            if coeff != 0
        ]
        forms.append(" + ".join(parts) if parts else "0")
    return tuple(forms)


def write_probe_script(
    system,
    path: Path,
    method: str,
    order: str,
    characteristic: int,
    linear_forms: tuple[str, ...],
) -> None:
    varlist = ",".join(system.variables)
    lines = [
        "// Generated by code/sage/probe_determinant_ideals.py",
        f"// method: {method}",
        f"// active_indices: {list(system.active_indices)}",
        f"// characteristic: {characteristic}",
        "timer = 1;",
        f"ring r = {characteristic},({varlist}),({singular_order(order)});",
        "",
    ]
    for i, expr in enumerate(system.equalities):
        lines.append(f"poly f{i} = {expr};")
    if system.equalities:
        lines.append(f"ideal I = {','.join(f'f{i}' for i in range(len(system.equalities)))};")
    else:
        lines.append("ideal I = 0;")
    for i, expr in enumerate(linear_forms):
        lines.append(f"poly l{i} = {expr};")
    if linear_forms:
        lines.append(f"I = I,{','.join(f'l{i}' for i in range(len(linear_forms)))};")

    lines.extend([
        "",
        f"{singular_string('method')};",
        f"{singular_string(method)};",
        f"{singular_string('nvars')};",
        f"{len(system.variables)};",
        f"{singular_string('neqs')};",
        f"{len(system.equalities)};",
        f"{singular_string('linear_sections')};",
        f"{len(linear_forms)};",
        f"{singular_string('max_degree')};",
        f"{max(system.equality_degrees) if system.equality_degrees else 0};",
        f"{singular_string('characteristic')};",
        f"{characteristic};",
    ])

    if method == "std":
        lines.extend([
            "option(redSB);",
            "ideal G = std(I);",
            f"{singular_string('basis_size')};",
            "size(G);",
            f"{singular_string('dimension')};",
            "dim(G);",
            f"{singular_string('degree')};",
            "degree(G);",
        ])
    elif method == "slimgb":
        lines.extend([
            "option(redSB);",
            "ideal G = slimgb(I);",
            f"{singular_string('basis_size')};",
            "size(G);",
            f"{singular_string('dimension')};",
            "dim(G);",
            f"{singular_string('degree')};",
            "degree(G);",
        ])
    elif method == "modstd":
        lines.extend([
            'LIB "modstd.lib";',
            "option(redSB);",
            "ideal G = modStd(I, 0);",
            f"{singular_string('basis_size')};",
            "size(G);",
            f"{singular_string('dimension')};",
            "dim(G);",
            f"{singular_string('degree')};",
            "degree(G);",
        ])
    elif method == "modslimgb":
        lines.extend([
            'LIB "modstd.lib";',
            "option(redSB);",
            'ideal G = modGB("slimgb", I, 0);',
            f"{singular_string('basis_size')};",
            "size(G);",
            f"{singular_string('dimension')};",
            "dim(G);",
            f"{singular_string('degree')};",
            "degree(G);",
        ])
    elif method == "facstd":
        lines.extend([
            "list L = facstd(I);",
            f"{singular_string('facstd_components')};",
            "size(L);",
            "int k;",
            "for (k=1; k<=size(L); k++) {",
            f"  {singular_string('component')};",
            "  k;",
            "  ideal G = std(L[k]);",
            f"  {singular_string('basis_size')};",
            "  size(G);",
            f"  {singular_string('dimension')};",
            "  dim(G);",
            f"  {singular_string('degree')};",
            "  degree(G);",
            "}",
        ])
    else:
        raise ValueError(f"unknown method: {method}")

    lines.extend([
        f"{singular_string('timer')};",
        "timer;",
        "quit;",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def parse_singular_output(stdout: str) -> dict:
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    parsed: dict[str, object] = {}
    keys = {
        "method",
        "nvars",
        "neqs",
        "linear_sections",
        "max_degree",
        "characteristic",
        "basis_size",
        "dimension",
        "degree",
        "facstd_components",
        "component",
        "timer",
    }
    i = 0
    components = []
    current_component = None
    pending_degree_target: dict[str, object] | None = None
    while i < len(lines):
        key = lines[i]
        if pending_degree_target is not None:
            match = re.search(r"degree \([^)]+\)\s*=\s*(-?\d+)", key)
            if match:
                pending_degree_target["degree_value"] = int(match.group(1))
                pending_degree_target = None
                i += 1
                continue
        if key not in keys or i + 1 >= len(lines):
            i += 1
            continue
        raw_value = lines[i + 1]
        try:
            value: object = int(raw_value)
        except ValueError:
            value = raw_value
        if key == "component":
            current_component = {"component": value}
            components.append(current_component)
        elif current_component is not None and key in {"basis_size", "dimension", "degree"}:
            current_component[key] = value
            if key == "degree":
                pending_degree_target = current_component
        else:
            parsed[key] = value
            if key == "degree":
                pending_degree_target = parsed
        i += 2
    if components:
        parsed["components"] = components
    return parsed


def run_singular(script_path: Path, singular_bin: str, timeout: int) -> dict:
    start = time.monotonic()
    try:
        completed = subprocess.run(
            [singular_bin, "-q", str(script_path)],
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        elapsed = time.monotonic() - start
        return {
            "timed_out": False,
            "exit_code": completed.returncode,
            "elapsed_seconds": elapsed,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "parsed": parse_singular_output(completed.stdout),
        }
    except subprocess.TimeoutExpired as exc:
        elapsed = time.monotonic() - start
        stdout = exc.stdout or ""
        stderr = exc.stderr or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode(errors="replace")
        if isinstance(stderr, bytes):
            stderr = stderr.decode(errors="replace")
        return {
            "timed_out": True,
            "exit_code": None,
            "elapsed_seconds": elapsed,
            "stdout": stdout,
            "stderr": stderr,
            "parsed": parse_singular_output(stdout),
        }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--active-indices")
    parser.add_argument("--mask")
    parser.add_argument("--known-label")
    parser.add_argument("--order", default="degrevlex")
    parser.add_argument("--invert-d", action="store_true")
    parser.add_argument("--methods", default="slimgb", help="comma-separated: std,slimgb,facstd")
    parser.add_argument("--timeout", type=int, default=120)
    parser.add_argument(
        "--characteristic",
        type=int,
        default=0,
        help="Singular coefficient characteristic; use a prime for modular probes",
    )
    parser.add_argument("--singular-bin", default=shutil.which("Singular") or "Singular")
    parser.add_argument("--out-prefix", default="code/sage/out/probe_det")
    parser.add_argument(
        "--linear-sections",
        type=int,
        default=0,
        help="add this many deterministic random affine linear equations",
    )
    parser.add_argument(
        "--linear-section-mode",
        choices=["random", "zero-sum-z"],
        default="random",
        help="zero-sum-z uses integer z-linear forms whose coefficients sum to zero",
    )
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--coefficient-bound", type=int, default=17)
    args = parser.parse_args()

    active = resolve_active(args)
    methods = tuple(x.strip() for x in args.methods.split(",") if x.strip())
    system = determinant_text_system(active, order=args.order, invert_d=args.invert_d)
    summary = text_system_summary(system)
    if args.linear_section_mode == "random":
        linear_forms = random_linear_forms(
            system.variables,
            count=args.linear_sections,
            seed=args.seed,
            characteristic=args.characteristic,
            coefficient_bound=args.coefficient_bound,
        )
    else:
        linear_forms = zero_sum_z_linear_forms(
            system.variables,
            count=args.linear_sections,
            seed=args.seed,
            coefficient_bound=args.coefficient_bound,
        )
    out_prefix = Path(args.out_prefix)
    out_prefix.parent.mkdir(parents=True, exist_ok=True)

    results = {
        "summary": summary,
        "timeout_seconds": args.timeout,
        "characteristic": args.characteristic,
        "linear_sections": args.linear_sections,
        "linear_section_mode": args.linear_section_mode,
        "linear_section_seed": args.seed,
        "linear_forms": list(linear_forms),
        "singular_bin": args.singular_bin,
        "methods": {},
    }
    for method in methods:
        script_path = out_prefix.with_name(f"{out_prefix.name}_{method}.sing")
        write_probe_script(
            system,
            script_path,
            method=method,
            order=args.order,
            characteristic=args.characteristic,
            linear_forms=linear_forms,
        )
        run = run_singular(script_path, args.singular_bin, args.timeout)
        results["methods"][method] = {
            "script": str(script_path),
            **run,
        }
        status = "timeout" if run["timed_out"] else f"exit {run['exit_code']}"
        parsed = run.get("parsed", {})
        dim = parsed.get("dimension", "?") if isinstance(parsed, dict) else "?"
        print(f"{method}: {status}, elapsed={run['elapsed_seconds']:.1f}s, dimension={dim}")

    result_path = out_prefix.with_suffix(".json")
    result_path.write_text(json.dumps(results, indent=1) + "\n")
    print(f"wrote {result_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
