#!/usr/bin/env python3
"""Probe a fixed-q Plucker ansatz component with Singular.

This is the Singular-backed counterpart of ``probe_plucker_q_value_component``.
The Sage implementation is convenient over finite fields, but the exact QQ
case benefits from Singular's modular Groebner backend.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

from sage.all import QQ

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from gtz63_semialgebraic import singular_order  # noqa: E402
from probe_determinant_ideals import singular_string  # noqa: E402
from probe_overtie_plucker_ansatz import CASES, build_system  # noqa: E402


def singular_poly(poly) -> str:
    return f"({poly})"


def parse_q_value(text: str):
    return QQ(text)


def equality_degree(text: str) -> int:
    """Small metadata-only degree heuristic for generated summaries."""
    if "^" not in text and "*" not in text:
        return 1
    degree = 1
    for chunk in text.replace("-", "+").split("+"):
        factors = [factor.strip() for factor in chunk.split("*") if factor.strip()]
        term_degree = 0
        for factor in factors:
            if "^" in factor:
                try:
                    term_degree += int(factor.rsplit("^", 1)[1])
                except ValueError:
                    term_degree += 1
            elif factor:
                term_degree += 1
        degree = max(degree, term_degree)
    return degree


def parse_extra_equalities(text: str) -> tuple[str, ...]:
    return tuple(item.strip() for item in re.split(r"[;,]", text) if item.strip())


def parse_target_polynomials(text: str) -> tuple[dict[str, str], ...]:
    return tuple(
        {"name": f"target_{i}", "polynomial": item.strip()}
        for i, item in enumerate(text.split(";"))
        if item.strip()
    )


def target_polynomials_from_relations_json(path: Path) -> tuple[dict[str, str], ...]:
    data = json.loads(path.read_text())
    targets = []
    for summary in data.get("summaries", []):
        expression = summary.get("expression")
        polynomial = summary.get("rational_polynomial")
        if not expression or not polynomial:
            continue
        substituted = re.sub(r"\bu\b", str(expression), polynomial)
        targets.append({"name": f"{expression}_eliminant", "polynomial": substituted})
    return tuple(targets)


def parse_methods(text: str) -> tuple[str, ...]:
    return tuple(item.strip() for item in text.split(",") if item.strip())


def write_script(
    *,
    path: Path,
    case_name: str,
    characteristic: int,
    order: str,
    method: str,
    q_value,
    extra_equalities: tuple[str, ...],
    target_polynomials: tuple[dict[str, str], ...],
    store_basis_path: Path | None,
) -> dict:
    ring, _z, _det_gram, polys, labels = build_system(case_name, characteristic, order)
    q = ring("q")
    equations = list(polys) + [q - ring.base_ring()(q_value)]
    equation_labels = list(labels) + [f"q:{q - ring.base_ring()(q_value)}"]
    equation_texts = [str(poly) for poly in equations] + list(extra_equalities)
    variables = tuple(str(name) for name in ring.variable_names())
    varlist = ",".join(variables)
    lines = [
        "// Generated by code/sage/probe_plucker_q_value_singular.py",
        f"// method: {method}",
        f"// case: {case_name}",
        f"// characteristic: {characteristic}",
        f"// q_value: {q_value}",
        "timer = 1;",
        f"ring r = {characteristic},({varlist}),({singular_order(order)});",
        "",
    ]
    for i, expr in enumerate(equation_texts):
        lines.append(f"poly f{i} = {singular_poly(expr)};")
    lines.append(f"ideal I = {','.join(f'f{i}' for i in range(len(equation_texts)))};")
    lines.extend(
        [
            "",
            f"{singular_string('method')};",
            f"{singular_string(method)};",
            f"{singular_string('case')};",
            f"{singular_string(case_name)};",
            f"{singular_string('nvars')};",
            f"{len(variables)};",
            f"{singular_string('neqs')};",
            f"{len(equation_texts)};",
            f"{singular_string('base_neqs')};",
            f"{len(equations)};",
            f"{singular_string('extra_neqs')};",
            f"{len(extra_equalities)};",
            f"{singular_string('max_degree')};",
            f"{max(equality_degree(expr) for expr in equation_texts)};",
            f"{singular_string('characteristic')};",
            f"{characteristic};",
            f"{singular_string('q_value')};",
            f"{singular_string(str(q_value))};",
            "option(redSB);",
        ]
    )
    if method == "std":
        lines.append("ideal G = std(I);")
    elif method == "slimgb":
        lines.append("ideal G = slimgb(I);")
    elif method == "modstd":
        lines.extend(['LIB "modstd.lib";', "ideal G = modStd(I, 0);"])
    elif method == "modslimgb":
        lines.extend(['LIB "modstd.lib";', 'ideal G = modGB("slimgb", I, 0);'])
    else:
        raise ValueError(f"unknown method {method!r}")
    lines.extend(
        [
            f"{singular_string('basis_size')};",
            "size(G);",
            f"{singular_string('dimension')};",
            "dim(G);",
            f"{singular_string('vdim')};",
            "vdim(G);",
            f"{singular_string('degree')};",
            "degree(G);",
        ]
    )
    if store_basis_path is not None:
        lines.extend(
            [
                f"write({singular_string(str(store_basis_path))}, G);",
                f"{singular_string('basis_path')};",
                f"{singular_string(str(store_basis_path))};",
            ]
        )
    for i, target in enumerate(target_polynomials):
        target_name = target.get("name") or f"target_{i}"
        target_poly = target["polynomial"]
        lines.extend(
            [
                f"poly target{i} = {singular_poly(target_poly)};",
                f"poly normal{i} = reduce(target{i}, G);",
                f"{singular_string(f'target_{i}_name')};",
                f"{singular_string(target_name)};",
                f"{singular_string(f'target_{i}_polynomial')};",
                f"{singular_string(target_poly)};",
                f"{singular_string(f'target_{i}_is_zero')};",
                f"normal{i} == 0;",
                f"{singular_string(f'target_{i}_terms')};",
                f"size(normal{i});",
                f"{singular_string(f'target_{i}_degree')};",
                f"deg(normal{i});",
                f"if (size(normal{i}) <= 20) {{",
                f"  {singular_string(f'target_{i}_normal_form')};",
                f"  normal{i};",
                "}",
            ]
        )
    lines.extend([f"{singular_string('timer')};", "timer;", "quit;"])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")
    return {
        "case": case_name,
        "characteristic": characteristic,
        "order": order,
        "method": method,
        "q_value": str(q_value),
        "variables": list(variables),
        "labels": equation_labels,
        "extra_equalities": list(extra_equalities),
        "target_polynomials": list(target_polynomials),
        "n_equations": len(equation_texts),
        "degrees": [equality_degree(expr) for expr in equation_texts],
        "script": str(path),
        "basis_path": str(store_basis_path) if store_basis_path is not None else None,
    }


def parse_singular_output(stdout: str) -> dict:
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    keys = {
        "method",
        "case",
        "nvars",
        "neqs",
        "base_neqs",
        "extra_neqs",
        "max_degree",
        "characteristic",
        "q_value",
        "basis_size",
        "dimension",
        "vdim",
        "degree",
        "basis_path",
        "timer",
    }
    dynamic_key = re.compile(r"target_\d+_(?:name|polynomial|is_zero|terms|degree|normal_form)")
    parsed: dict[str, object] = {}
    pending_degree = False
    i = 0
    while i < len(lines):
        line = lines[i]
        if pending_degree:
            match = re.search(r"degree \([^)]+\)\s*=\s*(-?\d+)", line)
            if match:
                parsed["degree_value"] = int(match.group(1))
                pending_degree = False
                i += 1
                continue
        if line not in keys and not dynamic_key.fullmatch(line):
            i += 1
            continue
        if i + 1 >= len(lines):
            i += 1
            continue
        raw = lines[i + 1]
        try:
            value: object = int(raw)
        except ValueError:
            value = raw
        parsed[line] = value
        if line == "degree":
            pending_degree = True
        i += 2
    return parsed


def run_singular(script_path: Path, singular_bin: str, timeout: int) -> dict:
    start = time.monotonic()
    try:
        completed = subprocess.run(
            [singular_bin, "-q", str(script_path)],
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        elapsed = time.monotonic() - start
        return {
            "timed_out": False,
            "exit_code": completed.returncode,
            "elapsed_seconds": elapsed,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "had_error": "? ERROR" in completed.stdout or "? error" in completed.stdout,
            "parsed": parse_singular_output(completed.stdout),
        }
    except subprocess.TimeoutExpired as exc:
        elapsed = time.monotonic() - start
        stdout = exc.stdout or ""
        stderr = exc.stderr or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode(errors="replace")
        if isinstance(stderr, bytes):
            stderr = stderr.decode(errors="replace")
        return {
            "timed_out": True,
            "exit_code": None,
            "elapsed_seconds": elapsed,
            "stdout": stdout,
            "stderr": stderr,
            "had_error": "? ERROR" in stdout or "? error" in stdout,
            "parsed": parse_singular_output(stdout),
        }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--case", choices=sorted(CASES), default="s8_79656")
    parser.add_argument("--characteristic", type=int, default=0)
    parser.add_argument("--q-value", default="5")
    parser.add_argument("--order", default="degrevlex")
    parser.add_argument("--methods", default="modslimgb")
    parser.add_argument("--extra-equalities", default="", help="semicolon-separated extra equations")
    parser.add_argument("--target-polynomials", default="", help="semicolon-separated polynomials to reduce")
    parser.add_argument("--relations-json", help="CRT relation JSON whose rational eliminants should be reduced")
    parser.add_argument("--timeout", type=int, default=900)
    parser.add_argument("--singular-bin", default=shutil.which("Singular") or "Singular")
    parser.add_argument("--store-basis", action="store_true")
    parser.add_argument("--out-prefix", default="code/sage/out/plucker_q_value_singular")
    args = parser.parse_args()

    q_value = parse_q_value(args.q_value)
    extra_equalities = parse_extra_equalities(args.extra_equalities)
    targets = list(parse_target_polynomials(args.target_polynomials))
    if args.relations_json:
        targets.extend(target_polynomials_from_relations_json(Path(args.relations_json)))
    target_polynomials = tuple(targets)
    out_prefix = Path(args.out_prefix)
    out_prefix.parent.mkdir(parents=True, exist_ok=True)
    results = {
        "case": args.case,
        "characteristic": args.characteristic,
        "q_value": str(q_value),
        "timeout_seconds": args.timeout,
        "singular_bin": args.singular_bin,
        "methods": {},
    }
    for method in parse_methods(args.methods):
        script_path = out_prefix.with_name(f"{out_prefix.name}_{method}.sing")
        basis_path = out_prefix.with_name(f"{out_prefix.name}_{method}_basis.txt") if args.store_basis else None
        metadata = write_script(
            path=script_path,
            case_name=args.case,
            characteristic=args.characteristic,
            order=args.order,
            method=method,
            q_value=q_value,
            extra_equalities=extra_equalities,
            target_polynomials=target_polynomials,
            store_basis_path=basis_path,
        )
        run = run_singular(script_path, args.singular_bin, args.timeout)
        results["methods"][method] = {**metadata, **run}
        parsed = run.get("parsed", {})
        status = "timeout" if run["timed_out"] else f"exit {run['exit_code']}"
        dim = parsed.get("dimension", "?") if isinstance(parsed, dict) else "?"
        degree = parsed.get("degree_value", "?") if isinstance(parsed, dict) else "?"
        basis = parsed.get("basis_size", "?") if isinstance(parsed, dict) else "?"
        print(
            f"{method}: {status}, elapsed={run['elapsed_seconds']:.1f}s, "
            f"dim={dim}, degree={degree}, basis={basis}"
        )

    result_path = out_prefix.with_suffix(".json")
    result_path.write_text(json.dumps(results, indent=1) + "\n")
    print(f"wrote {result_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
