#!/usr/bin/env python3
"""Reduce CAD obstruction relations modulo earlier branch ideals.

This is a direct certificate probe for the cascade:

    R0 on I_top,
    R1 on I + R0 + z0,
    R2 on I + R0 + z0 + R1 + z1.

If the normal form of a target relation is zero, then that relation is an
ordinary ideal consequence of the premise equations, so no component/saturation
argument is needed for that step.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import time
from dataclasses import replace
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from gtz63_semialgebraic import determinant_text_system, singular_order, text_system_summary  # noqa: E402
from probe_cad_obstruction_strata import equality_degree, parse_relation_specs  # noqa: E402
from probe_determinant_ideals import resolve_active, singular_string  # noqa: E402
from probe_minor_relation import minor_relation_text  # noqa: E402


def parse_equalities(text: str) -> tuple[str, ...]:
    return tuple(item.strip() for item in text.split(",") if item.strip())


def parse_one_relation(text: str) -> tuple[int, tuple[int, int], int, str]:
    specs = parse_relation_specs(text)
    if len(specs) != 1:
        raise SystemExit("--target-relation must contain exactly one active:rows:coefficient:variable entry")
    return specs[0]


def relation_text_from_spec(spec, order: str, invert_d: bool) -> tuple[str, int, dict]:
    active_index, rows, coefficient, variable = spec
    text, degree = minor_relation_text(
        active_index=active_index,
        minor_rows=rows,
        coefficient=coefficient,
        order=order,
        invert_d=invert_d,
        variable=variable,
    )
    return text, degree, {
        "active_index": active_index,
        "minor_rows": list(rows),
        "coefficient": coefficient,
        "variable": variable,
        "text": text,
        "degree": degree,
    }


def parse_methods(text: str) -> tuple[str, ...]:
    return tuple(item.strip() for item in text.split(",") if item.strip())


def write_nf_script(system, target: str, path: Path, method: str, order: str, characteristic: int) -> None:
    varlist = ",".join(system.variables)
    lines = [
        "// Generated by code/sage/probe_cad_relation_normal_forms.py",
        f"// method: {method}",
        f"// characteristic: {characteristic}",
        "timer = 1;",
        f"ring r = {characteristic},({varlist}),({singular_order(order)});",
        "",
    ]
    for i, expr in enumerate(system.equalities):
        lines.append(f"poly f{i} = {expr};")
    lines.append(f"ideal I = {','.join(f'f{i}' for i in range(len(system.equalities)))};")
    lines.append(f"poly target = {target};")
    lines.extend([
        "",
        f"{singular_string('method')};",
        f"{singular_string(method)};",
        f"{singular_string('nvars')};",
        f"{len(system.variables)};",
        f"{singular_string('neqs')};",
        f"{len(system.equalities)};",
        f"{singular_string('characteristic')};",
        f"{characteristic};",
        "option(redSB);",
    ])
    if method == "std":
        lines.append("ideal G = std(I);")
    elif method == "slimgb":
        lines.append("ideal G = slimgb(I);")
    elif method == "modstd":
        lines.extend(['LIB "modstd.lib";', "ideal G = modStd(I, 0);"])
    elif method == "modslimgb":
        lines.extend(['LIB "modstd.lib";', 'ideal G = modGB("slimgb", I, 0);'])
    else:
        raise ValueError(f"unknown method: {method}")
    lines.extend([
        f"{singular_string('basis_size')};",
        "size(G);",
        f"{singular_string('dimension')};",
        "dim(G);",
        f"{singular_string('degree')};",
        "degree(G);",
        "poly normal = reduce(target, G);",
        f"{singular_string('normal_is_zero')};",
        "normal == 0;",
        f"{singular_string('normal_terms')};",
        "size(normal);",
        f"{singular_string('normal_degree')};",
        "deg(normal);",
        "if (size(normal) <= 20) {",
        f"  {singular_string('normal_form')};",
        "  normal;",
        "}",
        f"{singular_string('timer')};",
        "timer;",
        "quit;",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def parse_singular_output(stdout: str) -> dict:
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    keys = {
        "method",
        "nvars",
        "neqs",
        "characteristic",
        "basis_size",
        "dimension",
        "degree",
        "normal_is_zero",
        "normal_terms",
        "normal_degree",
        "normal_form",
        "timer",
    }
    parsed: dict[str, object] = {}
    pending_degree = False
    i = 0
    while i < len(lines):
        line = lines[i]
        if pending_degree:
            match = re.search(r"degree \([^)]+\)\s*=\s*(-?\d+)", line)
            if match:
                parsed["degree_value"] = int(match.group(1))
                pending_degree = False
                i += 1
                continue
        if line not in keys or i + 1 >= len(lines):
            i += 1
            continue
        raw = lines[i + 1]
        try:
            value: object = int(raw)
        except ValueError:
            value = raw
        parsed[line] = value
        if line == "degree":
            pending_degree = True
        i += 2
    return parsed


def run_singular(script_path: Path, singular_bin: str, timeout: int) -> dict:
    start = time.monotonic()
    try:
        completed = subprocess.run(
            [singular_bin, "-q", str(script_path)],
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        elapsed = time.monotonic() - start
        return {
            "timed_out": False,
            "exit_code": completed.returncode,
            "elapsed_seconds": elapsed,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "parsed": parse_singular_output(completed.stdout),
        }
    except subprocess.TimeoutExpired as exc:
        elapsed = time.monotonic() - start
        stdout = exc.stdout or ""
        stderr = exc.stderr or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode(errors="replace")
        if isinstance(stderr, bytes):
            stderr = stderr.decode(errors="replace")
        return {
            "timed_out": True,
            "exit_code": None,
            "elapsed_seconds": elapsed,
            "stdout": stdout,
            "stderr": stderr,
            "parsed": parse_singular_output(stdout),
        }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--active-indices")
    parser.add_argument("--mask")
    parser.add_argument("--known-label")
    parser.add_argument("--order", default="degrevlex")
    parser.add_argument("--invert-d", action="store_true")
    parser.add_argument("--premise-relations", default="")
    parser.add_argument("--premise-equalities", default="")
    parser.add_argument("--target-relation", required=True)
    parser.add_argument("--methods", default="slimgb")
    parser.add_argument("--timeout", type=int, default=240)
    parser.add_argument("--characteristic", type=int, default=32003)
    parser.add_argument("--singular-bin", default=shutil.which("Singular") or "Singular")
    parser.add_argument("--out-prefix", default="code/sage/out/cad_relation_nf")
    args = parser.parse_args()

    active = resolve_active(args)
    system = determinant_text_system(active, order=args.order, invert_d=args.invert_d)
    premise_records = []
    premise_relations = []
    premise_degrees = []
    for spec in parse_relation_specs(args.premise_relations):
        relation, degree, record = relation_text_from_spec(spec, args.order, args.invert_d)
        premise_relations.append(relation)
        premise_degrees.append(degree)
        premise_records.append(record)
    premise_equalities = parse_equalities(args.premise_equalities)
    system = replace(
        system,
        mode=f"{system.mode}_nf_premise",
        equalities=system.equalities + tuple(premise_relations) + premise_equalities,
        equality_degrees=system.equality_degrees
        + tuple(premise_degrees)
        + tuple(equality_degree(eq) for eq in premise_equalities),
        metadata={
            **system.metadata,
            "premise_relations": premise_records,
            "premise_equalities": list(premise_equalities),
        },
    )
    target, target_degree, target_record = relation_text_from_spec(
        parse_one_relation(args.target_relation),
        args.order,
        args.invert_d,
    )

    out_prefix = Path(args.out_prefix)
    out_prefix.parent.mkdir(parents=True, exist_ok=True)
    results = {
        "summary": text_system_summary(system),
        "characteristic": args.characteristic,
        "timeout_seconds": args.timeout,
        "premise_relations": premise_records,
        "premise_equalities": list(premise_equalities),
        "target_relation": target_record,
        "target_degree": target_degree,
        "methods": {},
    }
    for method in parse_methods(args.methods):
        script_path = out_prefix.with_name(f"{out_prefix.name}_{method}.sing")
        write_nf_script(system, target, script_path, method, args.order, args.characteristic)
        run = run_singular(script_path, args.singular_bin, args.timeout)
        results["methods"][method] = {"script": str(script_path), **run}
        parsed = run.get("parsed", {})
        status = "timeout" if run["timed_out"] else f"exit {run['exit_code']}"
        print(
            f"{method}: {status}, elapsed={run['elapsed_seconds']:.1f}s, "
            f"normal_is_zero={parsed.get('normal_is_zero', '?') if isinstance(parsed, dict) else '?'}"
        )

    result_path = out_prefix.with_suffix(".json")
    result_path.write_text(json.dumps(results, indent=1) + "\n")
    print(f"wrote {result_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
