#!/usr/bin/env python3
"""Measure quotient-algebra span generated by a rectangular monomial grid."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from compute_q_power_relation import make_ring, monomial_key, vector_from_poly  # noqa: E402
from sage.all import Matrix  # noqa: E402


def parse_names(text: str) -> list[str]:
    names = [part.strip() for part in text.split(",") if part.strip()]
    if len(names) != 2:
        raise argparse.ArgumentTypeError("expected exactly two comma-separated names")
    return names


def parse_limits(text: str) -> list[int]:
    limits = [int(part.strip()) for part in text.split(",") if part.strip()]
    if len(limits) != 2 or min(limits) < 0:
        raise argparse.ArgumentTypeError("expected two nonnegative comma-separated limits")
    return limits


def power_table(element, gb, limit: int):
    powers = []
    current = element.parent()(1)
    for exponent in range(limit + 1):
        powers.append(current)
        if exponent < limit:
            current = (current * element).reduce(gb)
    return powers


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--basis-json", required=True)
    parser.add_argument("--generators", type=parse_names, required=True)
    parser.add_argument("--limits", type=parse_limits, required=True)
    parser.add_argument("--stop-at-full-rank", action="store_true")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    data = json.loads(Path(args.basis_json).read_text())
    ring = make_ring(data)
    field = ring.base_ring()
    gb = [ring(poly) for poly in data["basis"]]
    ideal = ring.ideal(gb)
    quotient_degree = int(data.get("degree") or ideal.vector_space_dimension())
    normal_basis = list(ideal.normal_basis())
    basis_index = {monomial_key(monomial): i for i, monomial in enumerate(normal_basis)}

    names = args.generators
    limits = args.limits
    first = ring(names[0])
    second = ring(names[1])
    first_powers = power_table(first, gb, limits[0])
    second_powers = power_table(second, gb, limits[1])

    print("=" * 78)
    print("GENERATOR SPAN SCREEN")
    print(f"basis json: {args.basis_json}")
    print(f"field: {field}")
    print(f"quotient degree: {quotient_degree}")
    print(f"generators: {names}")
    print(f"limits: {limits}")
    print(f"normal basis size: {len(normal_basis)}")

    vectors = []
    rows = []
    for second_power, second_poly in enumerate(second_powers):
        for first_power, first_poly in enumerate(first_powers):
            poly = (first_poly * second_poly).reduce(gb)
            vectors.append(vector_from_poly(poly, basis_index, field))
        matrix = Matrix(field, len(normal_basis), len(vectors), lambda i, j: vectors[j][i])
        rank = int(matrix.rank())
        rows.append(
            {
                names[1] + "_max_power": second_power,
                names[0] + "_max_power": limits[0],
                "columns": len(vectors),
                "rank": rank,
                "defect": quotient_degree - rank,
            }
        )
        print(
            f"{names[1]}^{second_power}: columns={len(vectors)} "
            f"rank={rank} defect={quotient_degree-rank}",
            flush=True,
        )
        if args.stop_at_full_rank and rank >= quotient_degree:
            break

    payload = {
        "basis_json": args.basis_json,
        "characteristic": int(data["characteristic"]),
        "variables": list(ring.variable_names()),
        "quotient_degree": quotient_degree,
        "normal_basis_size": len(normal_basis),
        "generators": names,
        "limits": limits,
        "rows": rows,
    }
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=1) + "\n")
    print("=" * 78)
    print(f"wrote {out}")
    print("=" * 78)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
