#!/usr/bin/env python3
"""Screen determinant curves for PSD-forcing minor-square relations.

For an active determinant ideal I, this searches over relations of the form

    M_T,ab + c * L^2 == 0 mod I

over a finite field, where M_T,ab is a 2x2 principal minor of the active block
6*N_TT - d*I and L is a supplied low-height polynomial, usually a coordinate or
a simple linear form.  If c lifts to a positive rational number, active PSD
would force L=0 on real points of that component.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

from sage.all import Matrix

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from gtz63_semialgebraic import (  # noqa: E402
    TRIPLES,
    active_block,
    determinant_text_system,
    make_ring,
    singular_order,
    standard_chart,
    text_system_summary,
)
from probe_determinant_ideals import resolve_active, singular_string  # noqa: E402


def parse_rows(text: str) -> tuple[int, int]:
    rows = tuple(int(x.strip()) for x in text.split(",") if x.strip())
    if len(rows) != 2 or len(set(rows)) != 2 or any(row < 0 or row >= 3 for row in rows):
        raise SystemExit("minor rows must be two distinct local row indices, e.g. 0,2")
    return rows


def active_minor_text(
    active_index: int,
    minor_rows: tuple[int, int],
    order: str,
    invert_d: bool,
) -> tuple[str, int]:
    ring = make_ring(include_h=False, inverse_count=1 if invert_d else 0, order=order)
    chart = standard_chart(ring, include_h=False, inverse_count=1 if invert_d else 0)
    block = active_block(chart, active_index)
    minor = Matrix(
        ring,
        2,
        2,
        lambda a, b: block[minor_rows[a], minor_rows[b]],
    ).det()
    return str(minor), int(minor.total_degree())


def parse_candidates(text: str) -> tuple[str, ...]:
    if not text.strip():
        return tuple(f"z{i}" for i in range(9))
    return tuple(item.strip() for item in text.split(",") if item.strip())


def write_screen_script(
    system,
    minors: list[dict],
    candidates: tuple[str, ...],
    path: Path,
    method: str,
    order: str,
    characteristic: int,
) -> None:
    varlist = ",".join(system.variables)
    lines = [
        "// Generated by code/sage/screen_curve_minor_square_relations.py",
        f"// method: {method}",
        f"// active_indices: {list(system.active_indices)}",
        f"// characteristic: {characteristic}",
        "timer = 1;",
        f"ring r = {characteristic},({varlist}),({singular_order(order)});",
        "",
    ]
    for i, expr in enumerate(system.equalities):
        lines.append(f"poly f{i} = {expr};")
    lines.append(f"ideal I = {','.join(f'f{i}' for i in range(len(system.equalities)))};")
    for i, record in enumerate(minors):
        lines.append(f"poly m{i} = {record['text']};")
    for i, expr in enumerate(candidates):
        lines.append(f"poly q{i} = ({expr})*({expr});")

    lines.extend([
        "",
        f"{singular_string('method')};",
        f"{singular_string(method)};",
        f"{singular_string('nvars')};",
        f"{len(system.variables)};",
        f"{singular_string('neqs')};",
        f"{len(system.equalities)};",
        f"{singular_string('minors')};",
        f"{len(minors)};",
        f"{singular_string('candidates')};",
        f"{len(candidates)};",
        f"{singular_string('characteristic')};",
        f"{characteristic};",
        "option(redSB);",
    ])
    if method == "std":
        lines.append("ideal G = std(I);")
    elif method == "slimgb":
        lines.append("ideal G = slimgb(I);")
    elif method == "modstd":
        lines.extend(['LIB "modstd.lib";', "ideal G = modStd(I, 0);"])
    elif method == "modslimgb":
        lines.extend(['LIB "modstd.lib";', 'ideal G = modGB("slimgb", I, 0);'])
    else:
        raise ValueError(f"unknown method: {method}")

    lines.extend([
        f"{singular_string('basis_size')};",
        "size(G);",
        f"{singular_string('dimension')};",
        "dim(G);",
        f"{singular_string('degree')};",
        "degree(G);",
        "int mi;",
        "int qi;",
        "number c;",
        "poly nm;",
        "poly nq;",
        "poly test;",
        "for (mi=0; mi<" + str(len(minors)) + "; mi++) {",
        "  execute(\"nm = reduce(m\" + string(mi) + \", G);\");",
        "  for (qi=0; qi<" + str(len(candidates)) + "; qi++) {",
        "    execute(\"nq = reduce(q\" + string(qi) + \", G);\");",
        "    if ((nm == 0) && (nq == 0)) {",
        f"      {singular_string('candidate_both_zero')};",
        "      mi;",
        "      qi;",
        "    }",
        "    if ((nm != 0) && (nq != 0) && (leadmonom(nm) == leadmonom(nq))) {",
        "      c = -leadcoef(nm)/leadcoef(nq);",
        "      test = nm + c*nq;",
        "      if (test == 0) {",
        f"        {singular_string('candidate')};",
        "        mi;",
        "        qi;",
        f"        {singular_string('coefficient')};",
        "        c;",
        f"        {singular_string('normal_terms')};",
        "        size(nm);",
        "      }",
        "    }",
        "  }",
        "}",
        f"{singular_string('timer')};",
        "timer;",
        "quit;",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n")


def parse_singular_output(stdout: str) -> dict:
    lines = [line.strip() for line in stdout.splitlines() if line.strip()]
    keys = {
        "method",
        "nvars",
        "neqs",
        "minors",
        "candidates",
        "characteristic",
        "basis_size",
        "dimension",
        "degree",
        "candidate",
        "candidate_both_zero",
        "coefficient",
        "normal_terms",
        "timer",
    }
    parsed: dict[str, object] = {"candidates_found": [], "both_zero": []}
    pending_degree = False
    i = 0
    while i < len(lines):
        line = lines[i]
        if pending_degree:
            match = re.search(r"degree \([^)]+\)\s*=\s*(-?\d+)", line)
            if match:
                parsed["degree_value"] = int(match.group(1))
                pending_degree = False
                i += 1
                continue
        if line == "candidate" and i + 5 < len(lines):
            record = {
                "minor_index": int(lines[i + 1]),
                "candidate_index": int(lines[i + 2]),
            }
            if lines[i + 3] == "coefficient":
                record["coefficient_mod_p"] = int(lines[i + 4])
            if i + 6 < len(lines) and lines[i + 5] == "normal_terms":
                record["normal_terms"] = int(lines[i + 6])
                i += 7
            else:
                i += 5
            parsed["candidates_found"].append(record)
            continue
        if line == "candidate_both_zero" and i + 2 < len(lines):
            parsed["both_zero"].append({
                "minor_index": int(lines[i + 1]),
                "candidate_index": int(lines[i + 2]),
            })
            i += 3
            continue
        if line not in keys or i + 1 >= len(lines):
            i += 1
            continue
        raw = lines[i + 1]
        try:
            value: object = int(raw)
        except ValueError:
            value = raw
        parsed[line] = value
        if line == "degree":
            pending_degree = True
        i += 2
    return parsed


def run_singular(script_path: Path, singular_bin: str, timeout: int) -> dict:
    start = time.monotonic()
    try:
        completed = subprocess.run(
            [singular_bin, "-q", str(script_path)],
            text=True,
            capture_output=True,
            timeout=timeout,
            check=False,
        )
        elapsed = time.monotonic() - start
        return {
            "timed_out": False,
            "exit_code": completed.returncode,
            "elapsed_seconds": elapsed,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
            "had_error": "? ERROR" in completed.stdout or "? error" in completed.stdout,
            "parsed": parse_singular_output(completed.stdout),
        }
    except subprocess.TimeoutExpired as exc:
        elapsed = time.monotonic() - start
        stdout = exc.stdout or ""
        stderr = exc.stderr or ""
        if isinstance(stdout, bytes):
            stdout = stdout.decode(errors="replace")
        if isinstance(stderr, bytes):
            stderr = stderr.decode(errors="replace")
        return {
            "timed_out": True,
            "exit_code": None,
            "elapsed_seconds": elapsed,
            "stdout": stdout,
            "stderr": stderr,
            "had_error": "? ERROR" in stdout or "? error" in stdout,
            "parsed": parse_singular_output(stdout),
        }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--active-indices")
    parser.add_argument("--mask")
    parser.add_argument("--known-label")
    parser.add_argument("--order", default="degrevlex")
    parser.add_argument("--invert-d", action="store_true")
    parser.add_argument("--method", choices=["std", "slimgb", "modstd", "modslimgb"], default="slimgb")
    parser.add_argument("--timeout", type=int, default=180)
    parser.add_argument("--characteristic", type=int, default=32003)
    parser.add_argument("--singular-bin", default=shutil.which("Singular") or "Singular")
    parser.add_argument(
        "--candidates",
        default="",
        help="comma-separated L expressions; each is screened as L^2. Default: z0,...,z8",
    )
    parser.add_argument("--out-prefix", default="code/sage/out/screen_curve_minor_square")
    args = parser.parse_args()

    active = resolve_active(args)
    system = determinant_text_system(active, order=args.order, invert_d=args.invert_d)
    minors = []
    for active_index in active:
        for minor_rows in ((0, 1), (0, 2), (1, 2)):
            text, degree = active_minor_text(active_index, minor_rows, args.order, args.invert_d)
            minors.append({
                "active_index": active_index,
                "active_triple": list(TRIPLES[active_index]),
                "minor_rows": list(minor_rows),
                "text": text,
                "degree": degree,
            })
    candidates = parse_candidates(args.candidates)

    out_prefix = Path(args.out_prefix)
    out_prefix.parent.mkdir(parents=True, exist_ok=True)
    script_path = out_prefix.with_suffix(".sing")
    write_screen_script(system, minors, candidates, script_path, args.method, args.order, args.characteristic)
    run = run_singular(script_path, args.singular_bin, args.timeout)
    parsed = run.get("parsed", {})
    enriched = []
    for record in parsed.get("candidates_found", []) if isinstance(parsed, dict) else []:
        enriched.append({
            **record,
            "minor": minors[record["minor_index"]],
            "linear_candidate": candidates[record["candidate_index"]],
        })
    both_zero = []
    for record in parsed.get("both_zero", []) if isinstance(parsed, dict) else []:
        both_zero.append({
            **record,
            "minor": minors[record["minor_index"]],
            "linear_candidate": candidates[record["candidate_index"]],
        })
    results = {
        "summary": text_system_summary(system),
        "characteristic": args.characteristic,
        "timeout_seconds": args.timeout,
        "method": args.method,
        "script": str(script_path),
        "minors": minors,
        "linear_candidates": list(candidates),
        "run": run,
        "candidate_relations": enriched,
        "both_zero_relations": both_zero,
    }
    result_path = out_prefix.with_suffix(".json")
    result_path.write_text(json.dumps(results, indent=1) + "\n")

    status = "timeout" if run["timed_out"] else f"exit {run['exit_code']}"
    dim = parsed.get("dimension", "?") if isinstance(parsed, dict) else "?"
    degree = parsed.get("degree_value", "?") if isinstance(parsed, dict) else "?"
    print(
        f"{args.method}: {status}, elapsed={run['elapsed_seconds']:.1f}s, "
        f"dim={dim}, degree={degree}, candidates={len(enriched)}, both_zero={len(both_zero)}"
    )
    for item in enriched[:20]:
        minor = item["minor"]
        print(
            "  active",
            minor["active_index"],
            "rows",
            "".join(str(x) for x in minor["minor_rows"]),
            "L",
            item["linear_candidate"],
            "c_mod_p",
            item.get("coefficient_mod_p"),
            "terms",
            item.get("normal_terms"),
        )
    print(f"wrote {result_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
