#!/usr/bin/env python3
"""Verify the structured size-6 ansatz q-eliminant by exact reduction.

The modular lex computations produce a candidate q-polynomial for the
``(c+d)^2=5`` branch.  This script checks the candidate over ``QQ`` by reducing
it against a characteristic-zero Groebner basis for the same branch ideal.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from sage.all import QQ, PolynomialRing


VARIABLES = ("a", "b", "c", "d", "q")
DEFAULT_NUISANCE = "(q-3)*(q-5)^2*(q^2-3*q+6)^2*(q^2-9*q+24)^2"


def parse_poly(ring, text: str):
    return ring(text.replace("^", "**"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--basis-json",
        default="code/sage/out/s6_ansatz_cplusd_QQ.json",
        help="QQ Groebner basis JSON generated by probe_s6_ansatz.py.",
    )
    parser.add_argument(
        "--residual-json",
        default="code/sage/out/s6_ansatz_cplusd_q_residual_crt_6primes.json",
        help="CRT residual q-factor JSON generated by reconstruct_univariate_crt.py.",
    )
    parser.add_argument(
        "--nuisance-factor",
        default=DEFAULT_NUISANCE,
        help="Known nuisance q-factor divided out before residual reconstruction.",
    )
    parser.add_argument("--out", default="code/sage/out/s6_ansatz_cplusd_eliminant_verify_QQ.json")
    args = parser.parse_args()

    basis_data = json.loads(Path(args.basis_json).read_text())
    residual_data = json.loads(Path(args.residual_json).read_text())
    if int(basis_data.get("characteristic", -1)) != 0:
        raise SystemExit("basis JSON is not over QQ")
    if basis_data.get("branch") != "cplusd_sq5":
        raise SystemExit(f"unexpected branch: {basis_data.get('branch')!r}")

    order = basis_data.get("order") or "degrevlex"
    ring = PolynomialRing(QQ, VARIABLES, order=order)
    gb = [parse_poly(ring, text) for text in basis_data["basis"]]
    residual_text = residual_data.get("rational_lift_polynomial")
    if not residual_text:
        raise SystemExit("residual JSON has no rational_lift_polynomial")
    residual = parse_poly(ring, residual_text)
    nuisance = parse_poly(ring, args.nuisance_factor)
    target = residual * nuisance

    print("=" * 78)
    print("S6 ANSATZ ELIMINANT VERIFICATION")
    print(f"basis: {args.basis_json}")
    print(f"basis size: {len(gb)}")
    print(f"order: {order}")
    print(f"target degree in q: {target.degree(ring('q'))}")
    print("reducing target against QQ branch basis...", flush=True)
    remainder = target.reduce(gb)
    is_zero = remainder == 0
    print(f"normal form is zero: {is_zero}")
    if not is_zero:
        print(f"normal form terms: {len(remainder.monomials())}")
        print(f"normal form degree: {remainder.total_degree()}")

    payload = {
        "basis_json": args.basis_json,
        "residual_json": args.residual_json,
        "branch": basis_data.get("branch"),
        "order": order,
        "basis_size": len(gb),
        "branch_dimension": basis_data.get("dimension"),
        "branch_degree": basis_data.get("degree"),
        "nuisance_factor": args.nuisance_factor,
        "residual_polynomial": str(residual),
        "target_polynomial": str(target),
        "target_q_degree": int(target.degree(ring("q"))),
        "normal_form_is_zero": bool(is_zero),
        "normal_form_terms": 0 if is_zero else len(remainder.monomials()),
        "normal_form_degree": None if is_zero else int(remainder.total_degree()),
        "normal_form": "0" if is_zero else str(remainder),
    }
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(payload, indent=1) + "\n")
    print(f"wrote {out}")
    print("=" * 78)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
